items:
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
  commentId: T:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
  id: AlertSettings
  parent: Microsoft.Azure.Management.SiteRecovery.Models
  children:
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.#ctor
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.#ctor(System.String)
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.Properties
  langs:
  - csharp
  - vb
  name: AlertSettings
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: AlertSettings
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettings.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nThe definition of an Alert.\r\n"
  example: []
  syntax:
    content: 'public class AlertSettings : ResourceBaseExtended'
    content.vb: >-
      Public Class AlertSettings

          Inherits ResourceBaseExtended
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.Properties
  commentId: P:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.Properties
  id: Properties
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
  langs:
  - csharp
  - vb
  name: Properties
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.Properties
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Properties
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettings.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nOptional.\r\n"
  example: []
  syntax:
    content: >-
      public AlertSettingsProperties Properties

      {

          get;

          set;

      }
    content.vb: Public Property Properties As AlertSettingsProperties
    parameters: []
    return:
      type: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.#ctor
  commentId: M:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
  langs:
  - csharp
  - vb
  name: AlertSettings()
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.AlertSettings()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettings.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nInitializes a new instance of the AlertSettings class.\r\n"
  example: []
  syntax:
    content: public AlertSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.#ctor(System.String)
  commentId: M:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
  langs:
  - csharp
  - vb
  name: AlertSettings(String)
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings.AlertSettings(System.String)
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettings.cs
    startLine: 55
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nInitializes a new instance of the AlertSettings class with required\r\narguments.\r\n"
  example: []
  syntax:
    content: public AlertSettings(string location)
    content.vb: Public Sub New(location As String)
    parameters:
    - id: location
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.SiteRecovery.Models
  isExternal: false
  name: Microsoft.Azure.Management.SiteRecovery.Models
  fullName: Microsoft.Azure.Management.SiteRecovery.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties
  parent: Microsoft.Azure.Management.SiteRecovery.Models
  isExternal: false
  name: AlertSettingsProperties
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
