items:
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse
  commentId: T:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse
  id: AlertSettingsListResponse
  parent: Microsoft.Azure.Management.SiteRecovery.Models
  children:
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.#ctor
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.Alerts
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.NextLink
  langs:
  - csharp
  - vb
  name: AlertSettingsListResponse
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: AlertSettingsListResponse
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsListResponse.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nModel class for list alerts response.\r\n"
  example: []
  syntax:
    content: 'public class AlertSettingsListResponse : OperationCommonResponse'
    content.vb: >-
      Public Class AlertSettingsListResponse

          Inherits OperationCommonResponse
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  inheritedMembers:
  - Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ClientRequestId
  - Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ContentType
  - Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.CorrelationRequestId
  - Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.Date
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.Alerts
  commentId: P:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.Alerts
  id: Alerts
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse
  langs:
  - csharp
  - vb
  name: Alerts
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.Alerts
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Alerts
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsListResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nOptional. The list of alerts.\r\n"
  example: []
  syntax:
    content: >-
      public IList<AlertSettings> Alerts

      {

          get;

          set;

      }
    content.vb: Public Property Alerts As IList(Of AlertSettings)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.NextLink
  commentId: P:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.NextLink
  id: NextLink
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse
  langs:
  - csharp
  - vb
  name: NextLink
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.NextLink
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: NextLink
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsListResponse.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nOptional. The value of next link.\r\n"
  example: []
  syntax:
    content: >-
      public string NextLink

      {

          get;

          set;

      }
    content.vb: Public Property NextLink As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.#ctor
  commentId: M:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse
  langs:
  - csharp
  - vb
  name: AlertSettingsListResponse()
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse.AlertSettingsListResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsListResponse.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nInitializes a new instance of the AlertSettingsListResponse class.\r\n"
  example: []
  syntax:
    content: public AlertSettingsListResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.SiteRecovery.Models
  isExternal: false
  name: Microsoft.Azure.Management.SiteRecovery.Models
  fullName: Microsoft.Azure.Management.SiteRecovery.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  parent: Microsoft.Azure.Management.SiteRecovery.Models
  isExternal: false
  name: OperationCommonResponse
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
- uid: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ClientRequestId
  parent: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  isExternal: false
  name: ClientRequestId
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ClientRequestId
- uid: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ContentType
  parent: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  isExternal: false
  name: ContentType
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ContentType
- uid: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.CorrelationRequestId
  parent: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  isExternal: false
  name: CorrelationRequestId
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.CorrelationRequestId
- uid: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.Date
  parent: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  isExternal: false
  name: Date
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.Date
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<AlertSettings>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings)
  name.vb: IList(Of AlertSettings)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
    name: AlertSettings
    fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
    name: AlertSettings
    fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
