items:
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse
  commentId: T:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse
  id: AlertSettingsResponse
  parent: Microsoft.Azure.Management.SiteRecovery.Models
  children:
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse.#ctor
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse.Alert
  langs:
  - csharp
  - vb
  name: AlertSettingsResponse
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: AlertSettingsResponse
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsResponse.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nModel class for alerts response.\r\n"
  example: []
  syntax:
    content: 'public class AlertSettingsResponse : OperationCommonResponse'
    content.vb: >-
      Public Class AlertSettingsResponse

          Inherits OperationCommonResponse
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  inheritedMembers:
  - Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ClientRequestId
  - Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ContentType
  - Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.CorrelationRequestId
  - Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.Date
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse.Alert
  commentId: P:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse.Alert
  id: Alert
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse
  langs:
  - csharp
  - vb
  name: Alert
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse.Alert
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Alert
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsResponse.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nOptional. The alert setting.\r\n"
  example: []
  syntax:
    content: >-
      public AlertSettings Alert

      {

          get;

          set;

      }
    content.vb: Public Property Alert As AlertSettings
    parameters: []
    return:
      type: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse.#ctor
  commentId: M:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse
  langs:
  - csharp
  - vb
  name: AlertSettingsResponse()
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse.AlertSettingsResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsResponse.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nInitializes a new instance of the AlertSettingsResponse class.\r\n"
  example: []
  syntax:
    content: public AlertSettingsResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.SiteRecovery.Models
  isExternal: false
  name: Microsoft.Azure.Management.SiteRecovery.Models
  fullName: Microsoft.Azure.Management.SiteRecovery.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  parent: Microsoft.Azure.Management.SiteRecovery.Models
  isExternal: false
  name: OperationCommonResponse
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
- uid: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ClientRequestId
  parent: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  isExternal: false
  name: ClientRequestId
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ClientRequestId
- uid: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ContentType
  parent: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  isExternal: false
  name: ContentType
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.ContentType
- uid: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.CorrelationRequestId
  parent: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  isExternal: false
  name: CorrelationRequestId
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.CorrelationRequestId
- uid: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.Date
  parent: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse
  isExternal: false
  name: Date
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.OperationCommonResponse.Date
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
  parent: Microsoft.Azure.Management.SiteRecovery.Models
  isExternal: false
  name: AlertSettings
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettings
