items:
- uid: Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations
  commentId: T:Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations
  id: IAlertSettingsOperations
  parent: Microsoft.Azure.Management.SiteRecovery
  children:
  - Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.ConfigureAsync(System.String,Microsoft.Azure.Management.SiteRecovery.Models.ConfigureAlertSettingsRequest,Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  - Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.GetAsync(System.String,Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  - Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.ListAsync(Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  langs:
  - csharp
  - vb
  name: IAlertSettingsOperations
  fullName: Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations
  type: Interface
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/IAlertSettingsOperations.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: IAlertSettingsOperations
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/IAlertSettingsOperations.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery
  summary: "\r\nDefinition of alert settings operations for the Site Recovery extension.\r\n"
  example: []
  syntax:
    content: public interface IAlertSettingsOperations
    content.vb: Public Interface IAlertSettingsOperations
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.ConfigureAsync(System.String,Microsoft.Azure.Management.SiteRecovery.Models.ConfigureAlertSettingsRequest,Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.ConfigureAsync(System.String,Microsoft.Azure.Management.SiteRecovery.Models.ConfigureAlertSettingsRequest,Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  id: ConfigureAsync(System.String,Microsoft.Azure.Management.SiteRecovery.Models.ConfigureAlertSettingsRequest,Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  parent: Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations
  langs:
  - csharp
  - vb
  name: ConfigureAsync(String, ConfigureAlertSettingsRequest, CustomRequestHeaders, CancellationToken)
  fullName: Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.ConfigureAsync(System.String, Microsoft.Azure.Management.SiteRecovery.Models.ConfigureAlertSettingsRequest, Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/IAlertSettingsOperations.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ConfigureAsync
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/IAlertSettingsOperations.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery
  summary: "\r\nUpdates the alert settings for the vault.\r\n"
  example: []
  syntax:
    content: Task<AlertSettingsResponse> ConfigureAsync(string alertSettingsName, ConfigureAlertSettingsRequest input, CustomRequestHeaders customRequestHeaders, CancellationToken cancellationToken)
    content.vb: Function ConfigureAsync(alertSettingsName As String, input As ConfigureAlertSettingsRequest, customRequestHeaders As CustomRequestHeaders, cancellationToken As CancellationToken) As Task(Of AlertSettingsResponse)
    parameters:
    - id: alertSettingsName
      type: System.String
      description: "\r\nAlert Settings name.\r\n"
    - id: input
      type: Microsoft.Azure.Management.SiteRecovery.Models.ConfigureAlertSettingsRequest
      description: "\r\nConfigure Alerts Request.\r\n"
    - id: customRequestHeaders
      type: Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders
      description: "\r\nRequest header parameters.\r\n"
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: "\r\nCancellation token.\r\n"
    return:
      type: System.Threading.Tasks.Task{Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse}
      description: "\r\nModel class for alerts response.\r\n"
- uid: Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.GetAsync(System.String,Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.GetAsync(System.String,Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  id: GetAsync(System.String,Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  parent: Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations
  langs:
  - csharp
  - vb
  name: GetAsync(String, CustomRequestHeaders, CancellationToken)
  fullName: Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.GetAsync(System.String, Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/IAlertSettingsOperations.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: GetAsync
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/IAlertSettingsOperations.cs
    startLine: 69
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery
  summary: "\r\nUpdates the alert settings for the vault.\r\n"
  example: []
  syntax:
    content: Task<AlertSettingsResponse> GetAsync(string alertSettingsName, CustomRequestHeaders customRequestHeaders, CancellationToken cancellationToken)
    content.vb: Function GetAsync(alertSettingsName As String, customRequestHeaders As CustomRequestHeaders, cancellationToken As CancellationToken) As Task(Of AlertSettingsResponse)
    parameters:
    - id: alertSettingsName
      type: System.String
      description: "\r\nAlert Settings name.\r\n"
    - id: customRequestHeaders
      type: Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders
      description: "\r\nRequest header parameters.\r\n"
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: "\r\nCancellation token.\r\n"
    return:
      type: System.Threading.Tasks.Task{Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse}
      description: "\r\nModel class for alerts response.\r\n"
- uid: Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.ListAsync(Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.ListAsync(Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  id: ListAsync(Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders,System.Threading.CancellationToken)
  parent: Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations
  langs:
  - csharp
  - vb
  name: ListAsync(CustomRequestHeaders, CancellationToken)
  fullName: Microsoft.Azure.Management.SiteRecovery.IAlertSettingsOperations.ListAsync(Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/IAlertSettingsOperations.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ListAsync
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/IAlertSettingsOperations.cs
    startLine: 83
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery
  summary: "\r\nGet the list of events under the vault.\r\n"
  example: []
  syntax:
    content: Task<AlertSettingsListResponse> ListAsync(CustomRequestHeaders customRequestHeaders, CancellationToken cancellationToken)
    content.vb: Function ListAsync(customRequestHeaders As CustomRequestHeaders, cancellationToken As CancellationToken) As Task(Of AlertSettingsListResponse)
    parameters:
    - id: customRequestHeaders
      type: Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders
      description: "\r\nRequest header parameters.\r\n"
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: "\r\nCancellation token.\r\n"
    return:
      type: System.Threading.Tasks.Task{Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse}
      description: "\r\nModel class for list alerts response.\r\n"
references:
- uid: Microsoft.Azure.Management.SiteRecovery
  isExternal: false
  name: Microsoft.Azure.Management.SiteRecovery
  fullName: Microsoft.Azure.Management.SiteRecovery
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.SiteRecovery.Models.ConfigureAlertSettingsRequest
  parent: Microsoft.Azure.Management.SiteRecovery.Models
  isExternal: false
  name: ConfigureAlertSettingsRequest
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.ConfigureAlertSettingsRequest
- uid: Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders
  parent: Microsoft.Azure.Management.SiteRecovery.Models
  isExternal: false
  name: CustomRequestHeaders
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.CustomRequestHeaders
- uid: System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  name: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Threading.Tasks.Task{Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<AlertSettingsResponse>
  fullName: System.Threading.Tasks.Task<Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse>
  fullname.vb: System.Threading.Tasks.Task(Of Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse)
  name.vb: Task(Of AlertSettingsResponse)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse
    name: AlertSettingsResponse
    fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse
    name: AlertSettingsResponse
    fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsResponse
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.SiteRecovery.Models
  isExternal: false
  name: Microsoft.Azure.Management.SiteRecovery.Models
  fullName: Microsoft.Azure.Management.SiteRecovery.Models
- uid: System.Threading
  isExternal: false
  name: System.Threading
  fullName: System.Threading
- uid: System.Threading.Tasks.Task`1
  parent: System.Threading.Tasks
  isExternal: true
  name: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  fullname.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - name: TResult
    fullName: TResult
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: TResult
    fullName: TResult
  - name: )
    fullName: )
- uid: System.Threading.Tasks
  isExternal: false
  name: System.Threading.Tasks
  fullName: System.Threading.Tasks
- uid: System.Threading.Tasks.Task{Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<AlertSettingsListResponse>
  fullName: System.Threading.Tasks.Task<Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse>
  fullname.vb: System.Threading.Tasks.Task(Of Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse)
  name.vb: Task(Of AlertSettingsListResponse)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse
    name: AlertSettingsListResponse
    fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse
    name: AlertSettingsListResponse
    fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsListResponse
  - name: )
    fullName: )
