items:
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties
  commentId: T:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties
  id: AlertSettingsProperties
  parent: Microsoft.Azure.Management.SiteRecovery.Models
  children:
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.#ctor
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.CustomEmailAddresses
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.Locale
  - Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.SendToOwners
  langs:
  - csharp
  - vb
  name: AlertSettingsProperties
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsProperties.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: AlertSettingsProperties
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsProperties.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nThe proprties of an alert.\r\n"
  example: []
  syntax:
    content: public class AlertSettingsProperties
    content.vb: Public Class AlertSettingsProperties
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.CustomEmailAddresses
  commentId: P:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.CustomEmailAddresses
  id: CustomEmailAddresses
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties
  langs:
  - csharp
  - vb
  name: CustomEmailAddresses
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.CustomEmailAddresses
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsProperties.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: CustomEmailAddresses
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsProperties.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nOptional. The custom email address for sending emails.\r\n"
  example: []
  syntax:
    content: >-
      public IList<string> CustomEmailAddresses

      {

          get;

          set;

      }
    content.vb: Public Property CustomEmailAddresses As IList(Of String)
    parameters: []
    return:
      type: System.Collections.Generic.IList{System.String}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.Locale
  commentId: P:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.Locale
  id: Locale
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties
  langs:
  - csharp
  - vb
  name: Locale
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.Locale
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsProperties.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Locale
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsProperties.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nOptional. The locale for the email notification.\r\n"
  example: []
  syntax:
    content: >-
      public string Locale

      {

          get;

          set;

      }
    content.vb: Public Property Locale As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.SendToOwners
  commentId: P:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.SendToOwners
  id: SendToOwners
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties
  langs:
  - csharp
  - vb
  name: SendToOwners
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.SendToOwners
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsProperties.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: SendToOwners
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsProperties.cs
    startLine: 61
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nOptional. A value indicating whether to send email to subscription\r\nowners.\r\n"
  example: []
  syntax:
    content: >-
      public string SendToOwners

      {

          get;

          set;

      }
    content.vb: Public Property SendToOwners As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.#ctor
  commentId: M:Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties
  langs:
  - csharp
  - vb
  name: AlertSettingsProperties()
  fullName: Microsoft.Azure.Management.SiteRecovery.Models.AlertSettingsProperties.AlertSettingsProperties()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsProperties.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/SiteRecovery/SiteRecoveryManagement/Generated/Models/AlertSettingsProperties.cs
    startLine: 70
  assemblies:
  - Microsoft.Azure.Management.SiteRecovery
  namespace: Microsoft.Azure.Management.SiteRecovery.Models
  summary: "\r\nInitializes a new instance of the AlertSettingsProperties class.\r\n"
  example: []
  syntax:
    content: public AlertSettingsProperties()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.SiteRecovery.Models
  isExternal: false
  name: Microsoft.Azure.Management.SiteRecovery.Models
  fullName: Microsoft.Azure.Management.SiteRecovery.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.IList{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<String>
  fullName: System.Collections.Generic.IList<System.String>
  fullname.vb: System.Collections.Generic.IList(Of System.String)
  name.vb: IList(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
