items:
- uid: Microsoft.Azure.Common.Authentication.PublishSettingsImporter
  commentId: T:Microsoft.Azure.Common.Authentication.PublishSettingsImporter
  id: PublishSettingsImporter
  parent: Microsoft.Azure.Common.Authentication
  children:
  - Microsoft.Azure.Common.Authentication.PublishSettingsImporter.ImportAzureSubscription(System.IO.Stream,Microsoft.Azure.Common.Authentication.ProfileClient,System.String)
  langs:
  - csharp
  - vb
  name: PublishSettingsImporter
  fullName: Microsoft.Azure.Common.Authentication.PublishSettingsImporter
  type: Class
  source:
    remote:
      path: src/src/Authentication/Common.Authentication/Common/PublishSettingsImporter.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: PublishSettingsImporter
    path: src/src/Authentication/Common.Authentication/Common/PublishSettingsImporter.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Common.Authentication
  namespace: Microsoft.Azure.Common.Authentication
  summary: "\r\nClass that handles loading publishsettings files\r\nand turning them into AzureSubscription objects.\r\n"
  example: []
  syntax:
    content: public class PublishSettingsImporter
    content.vb: Public Class PublishSettingsImporter
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Common.Authentication.PublishSettingsImporter.ImportAzureSubscription(System.IO.Stream,Microsoft.Azure.Common.Authentication.ProfileClient,System.String)
  commentId: M:Microsoft.Azure.Common.Authentication.PublishSettingsImporter.ImportAzureSubscription(System.IO.Stream,Microsoft.Azure.Common.Authentication.ProfileClient,System.String)
  id: ImportAzureSubscription(System.IO.Stream,Microsoft.Azure.Common.Authentication.ProfileClient,System.String)
  parent: Microsoft.Azure.Common.Authentication.PublishSettingsImporter
  langs:
  - csharp
  - vb
  name: ImportAzureSubscription(Stream, ProfileClient, String)
  fullName: Microsoft.Azure.Common.Authentication.PublishSettingsImporter.ImportAzureSubscription(System.IO.Stream, Microsoft.Azure.Common.Authentication.ProfileClient, System.String)
  type: Method
  source:
    remote:
      path: src/src/Authentication/Common.Authentication/Common/PublishSettingsImporter.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ImportAzureSubscription
    path: src/src/Authentication/Common.Authentication/Common/PublishSettingsImporter.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Common.Authentication
  namespace: Microsoft.Azure.Common.Authentication
  syntax:
    content: public static IEnumerable<AzureSubscription> ImportAzureSubscription(Stream stream, ProfileClient azureProfileClient, string environment)
    content.vb: Public Shared Function ImportAzureSubscription(stream As Stream, azureProfileClient As ProfileClient, environment As String) As IEnumerable(Of AzureSubscription)
    parameters:
    - id: stream
      type: System.IO.Stream
    - id: azureProfileClient
      type: Microsoft.Azure.Common.Authentication.ProfileClient
    - id: environment
      type: System.String
    return:
      type: System.Collections.Generic.IEnumerable{Microsoft.Azure.Common.Authentication.Models.AzureSubscription}
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Microsoft.Azure.Common.Authentication
  isExternal: false
  name: Microsoft.Azure.Common.Authentication
  fullName: Microsoft.Azure.Common.Authentication
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  fullName: System.IO.Stream
- uid: Microsoft.Azure.Common.Authentication.ProfileClient
  parent: Microsoft.Azure.Common.Authentication
  isExternal: false
  name: ProfileClient
  fullName: Microsoft.Azure.Common.Authentication.ProfileClient
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Collections.Generic.IEnumerable{Microsoft.Azure.Common.Authentication.Models.AzureSubscription}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<AzureSubscription>
  fullName: System.Collections.Generic.IEnumerable<Microsoft.Azure.Common.Authentication.Models.AzureSubscription>
  fullname.vb: System.Collections.Generic.IEnumerable(Of Microsoft.Azure.Common.Authentication.Models.AzureSubscription)
  name.vb: IEnumerable(Of AzureSubscription)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Common.Authentication.Models.AzureSubscription
    name: AzureSubscription
    fullName: Microsoft.Azure.Common.Authentication.Models.AzureSubscription
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Common.Authentication.Models.AzureSubscription
    name: AzureSubscription
    fullName: Microsoft.Azure.Common.Authentication.Models.AzureSubscription
  - name: )
    fullName: )
- uid: System.IO
  isExternal: false
  name: System.IO
  fullName: System.IO
- uid: System.Collections.Generic.IEnumerable`1
  parent: System.Collections.Generic
  isExternal: true
  name: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  fullname.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
