items:
- uid: Microsoft.Azure.Graph.RBAC.IApplicationOperations
  commentId: T:Microsoft.Azure.Graph.RBAC.IApplicationOperations
  id: IApplicationOperations
  parent: Microsoft.Azure.Graph.RBAC
  children:
  - Microsoft.Azure.Graph.RBAC.IApplicationOperations.CreateAsync(Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters,System.Threading.CancellationToken)
  - Microsoft.Azure.Graph.RBAC.IApplicationOperations.DeleteAsync(System.String,System.Threading.CancellationToken)
  - Microsoft.Azure.Graph.RBAC.IApplicationOperations.GetAsync(System.String,System.Threading.CancellationToken)
  - Microsoft.Azure.Graph.RBAC.IApplicationOperations.ListAsync(Microsoft.Azure.Graph.RBAC.Models.ApplicationFilterParameters,System.Threading.CancellationToken)
  - Microsoft.Azure.Graph.RBAC.IApplicationOperations.UpdateAsync(System.String,Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters,System.Threading.CancellationToken)
  langs:
  - csharp
  - vb
  name: IApplicationOperations
  fullName: Microsoft.Azure.Graph.RBAC.IApplicationOperations
  type: Interface
  source:
    remote:
      path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: IApplicationOperations
    path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
    startLine: 36
  assemblies:
  - Microsoft.Azure.Graph.RBAC
  namespace: Microsoft.Azure.Graph.RBAC
  summary: "\r\nOperations for working with applications in Azure Active Directory\r\nGraph API.  (see\r\nhttp://msdn.microsoft.com/en-us/library/azure/hh974476.aspx for more\r\ninformation)\r\n"
  example: []
  syntax:
    content: public interface IApplicationOperations
    content.vb: Public Interface IApplicationOperations
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Graph.RBAC.IApplicationOperations.CreateAsync(Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters,System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Graph.RBAC.IApplicationOperations.CreateAsync(Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters,System.Threading.CancellationToken)
  id: CreateAsync(Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters,System.Threading.CancellationToken)
  parent: Microsoft.Azure.Graph.RBAC.IApplicationOperations
  langs:
  - csharp
  - vb
  name: CreateAsync(ApplicationCreateParameters, CancellationToken)
  fullName: Microsoft.Azure.Graph.RBAC.IApplicationOperations.CreateAsync(Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: CreateAsync
    path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Graph.RBAC
  namespace: Microsoft.Azure.Graph.RBAC
  summary: "\r\nCreate a new application.  (see\r\nhttp://msdn.microsoft.com/en-us/library/azure/hh974476.aspx for\r\nmore information)\r\n"
  example: []
  syntax:
    content: Task<ApplicationGetResult> CreateAsync(ApplicationCreateParameters parameters, CancellationToken cancellationToken)
    content.vb: Function CreateAsync(parameters As ApplicationCreateParameters, cancellationToken As CancellationToken) As Task(Of ApplicationGetResult)
    parameters:
    - id: parameters
      type: Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters
      description: "\r\nParameters to create an application.\r\n"
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: "\r\nCancellation token.\r\n"
    return:
      type: System.Threading.Tasks.Task{Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult}
      description: "\r\nServer response for Get application information API call\r\n"
- uid: Microsoft.Azure.Graph.RBAC.IApplicationOperations.DeleteAsync(System.String,System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Graph.RBAC.IApplicationOperations.DeleteAsync(System.String,System.Threading.CancellationToken)
  id: DeleteAsync(System.String,System.Threading.CancellationToken)
  parent: Microsoft.Azure.Graph.RBAC.IApplicationOperations
  langs:
  - csharp
  - vb
  name: DeleteAsync(String, CancellationToken)
  fullName: Microsoft.Azure.Graph.RBAC.IApplicationOperations.DeleteAsync(System.String, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: DeleteAsync
    path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
    startLine: 69
  assemblies:
  - Microsoft.Azure.Graph.RBAC
  namespace: Microsoft.Azure.Graph.RBAC
  summary: "\r\nDelete an application.  (see\r\nhttp://msdn.microsoft.com/en-us/library/azure/hh974476.aspx for\r\nmore information)\r\n"
  example: []
  syntax:
    content: Task<AzureOperationResponse> DeleteAsync(string applicationObjectId, CancellationToken cancellationToken)
    content.vb: Function DeleteAsync(applicationObjectId As String, cancellationToken As CancellationToken) As Task(Of AzureOperationResponse)
    parameters:
    - id: applicationObjectId
      type: System.String
      description: "\r\nApplication object id\r\n"
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: "\r\nCancellation token.\r\n"
    return:
      type: System.Threading.Tasks.Task{AzureOperationResponse}
      description: "\r\nA standard service response including an HTTP status code and\r\nrequest ID.\r\n"
- uid: Microsoft.Azure.Graph.RBAC.IApplicationOperations.GetAsync(System.String,System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Graph.RBAC.IApplicationOperations.GetAsync(System.String,System.Threading.CancellationToken)
  id: GetAsync(System.String,System.Threading.CancellationToken)
  parent: Microsoft.Azure.Graph.RBAC.IApplicationOperations
  langs:
  - csharp
  - vb
  name: GetAsync(String, CancellationToken)
  fullName: Microsoft.Azure.Graph.RBAC.IApplicationOperations.GetAsync(System.String, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: GetAsync
    path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
    startLine: 85
  assemblies:
  - Microsoft.Azure.Graph.RBAC
  namespace: Microsoft.Azure.Graph.RBAC
  summary: "\r\nGet an application by object Id.  (see\r\nhttp://msdn.microsoft.com/en-us/library/azure/hh974476.aspx for\r\nmore information)\r\n"
  example: []
  syntax:
    content: Task<ApplicationGetResult> GetAsync(string applicationObjectId, CancellationToken cancellationToken)
    content.vb: Function GetAsync(applicationObjectId As String, cancellationToken As CancellationToken) As Task(Of ApplicationGetResult)
    parameters:
    - id: applicationObjectId
      type: System.String
      description: "\r\nApplication object id\r\n"
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: "\r\nCancellation token.\r\n"
    return:
      type: System.Threading.Tasks.Task{Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult}
      description: "\r\nServer response for Get application information API call\r\n"
- uid: Microsoft.Azure.Graph.RBAC.IApplicationOperations.ListAsync(Microsoft.Azure.Graph.RBAC.Models.ApplicationFilterParameters,System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Graph.RBAC.IApplicationOperations.ListAsync(Microsoft.Azure.Graph.RBAC.Models.ApplicationFilterParameters,System.Threading.CancellationToken)
  id: ListAsync(Microsoft.Azure.Graph.RBAC.Models.ApplicationFilterParameters,System.Threading.CancellationToken)
  parent: Microsoft.Azure.Graph.RBAC.IApplicationOperations
  langs:
  - csharp
  - vb
  name: ListAsync(ApplicationFilterParameters, CancellationToken)
  fullName: Microsoft.Azure.Graph.RBAC.IApplicationOperations.ListAsync(Microsoft.Azure.Graph.RBAC.Models.ApplicationFilterParameters, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ListAsync
    path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
    startLine: 101
  assemblies:
  - Microsoft.Azure.Graph.RBAC
  namespace: Microsoft.Azure.Graph.RBAC
  summary: "\r\nGet applications by filters.  (see\r\nhttp://msdn.microsoft.com/en-us/library/azure/hh974476.aspx for\r\nmore information)\r\n"
  example: []
  syntax:
    content: Task<ApplicationListResult> ListAsync(ApplicationFilterParameters parameters, CancellationToken cancellationToken)
    content.vb: Function ListAsync(parameters As ApplicationFilterParameters, cancellationToken As CancellationToken) As Task(Of ApplicationListResult)
    parameters:
    - id: parameters
      type: Microsoft.Azure.Graph.RBAC.Models.ApplicationFilterParameters
      description: "\r\nApplication filter parameters\r\n"
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: "\r\nCancellation token.\r\n"
    return:
      type: System.Threading.Tasks.Task{Microsoft.Azure.Graph.RBAC.Models.ApplicationListResult}
      description: "\r\nServer response for List application information API call\r\n"
- uid: Microsoft.Azure.Graph.RBAC.IApplicationOperations.UpdateAsync(System.String,Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters,System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Graph.RBAC.IApplicationOperations.UpdateAsync(System.String,Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters,System.Threading.CancellationToken)
  id: UpdateAsync(System.String,Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters,System.Threading.CancellationToken)
  parent: Microsoft.Azure.Graph.RBAC.IApplicationOperations
  langs:
  - csharp
  - vb
  name: UpdateAsync(String, ApplicationCreateParameters, CancellationToken)
  fullName: Microsoft.Azure.Graph.RBAC.IApplicationOperations.UpdateAsync(System.String, Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: UpdateAsync
    path: src/src/Graph.RBAC/Graph.RBAC/Generated/IApplicationOperations.cs
    startLine: 121
  assemblies:
  - Microsoft.Azure.Graph.RBAC
  namespace: Microsoft.Azure.Graph.RBAC
  summary: "\r\nUpdate existing application.  (see\r\nhttp://msdn.microsoft.com/en-us/library/azure/hh974476.aspx for\r\nmore information)\r\n"
  example: []
  syntax:
    content: Task<AzureOperationResponse> UpdateAsync(string applicationObjectId, ApplicationCreateParameters parameters, CancellationToken cancellationToken)
    content.vb: Function UpdateAsync(applicationObjectId As String, parameters As ApplicationCreateParameters, cancellationToken As CancellationToken) As Task(Of AzureOperationResponse)
    parameters:
    - id: applicationObjectId
      type: System.String
      description: "\r\nApplication object id\r\n"
    - id: parameters
      type: Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters
      description: "\r\nParameters to create an application.\r\n"
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: "\r\nCancellation token.\r\n"
    return:
      type: System.Threading.Tasks.Task{AzureOperationResponse}
      description: "\r\nA standard service response including an HTTP status code and\r\nrequest ID.\r\n"
references:
- uid: Microsoft.Azure.Graph.RBAC
  isExternal: false
  name: Microsoft.Azure.Graph.RBAC
  fullName: Microsoft.Azure.Graph.RBAC
- uid: Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters
  parent: Microsoft.Azure.Graph.RBAC.Models
  isExternal: false
  name: ApplicationCreateParameters
  fullName: Microsoft.Azure.Graph.RBAC.Models.ApplicationCreateParameters
- uid: System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  name: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Threading.Tasks.Task{Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<ApplicationGetResult>
  fullName: System.Threading.Tasks.Task<Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult>
  fullname.vb: System.Threading.Tasks.Task(Of Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult)
  name.vb: Task(Of ApplicationGetResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult
    name: ApplicationGetResult
    fullName: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult
    name: ApplicationGetResult
    fullName: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult
  - name: )
    fullName: )
- uid: Microsoft.Azure.Graph.RBAC.Models
  isExternal: false
  name: Microsoft.Azure.Graph.RBAC.Models
  fullName: Microsoft.Azure.Graph.RBAC.Models
- uid: System.Threading
  isExternal: false
  name: System.Threading
  fullName: System.Threading
- uid: System.Threading.Tasks.Task`1
  parent: System.Threading.Tasks
  isExternal: true
  name: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  fullname.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - name: TResult
    fullName: TResult
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: TResult
    fullName: TResult
  - name: )
    fullName: )
- uid: System.Threading.Tasks
  isExternal: false
  name: System.Threading.Tasks
  fullName: System.Threading.Tasks
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Threading.Tasks.Task{AzureOperationResponse}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<AzureOperationResponse>
  fullName: System.Threading.Tasks.Task<AzureOperationResponse>
  fullname.vb: System.Threading.Tasks.Task(Of AzureOperationResponse)
  name.vb: Task(Of AzureOperationResponse)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - uid: AzureOperationResponse
    name: AzureOperationResponse
    fullName: AzureOperationResponse
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: AzureOperationResponse
    name: AzureOperationResponse
    fullName: AzureOperationResponse
    isExternal: true
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Graph.RBAC.Models.ApplicationFilterParameters
  parent: Microsoft.Azure.Graph.RBAC.Models
  isExternal: false
  name: ApplicationFilterParameters
  fullName: Microsoft.Azure.Graph.RBAC.Models.ApplicationFilterParameters
- uid: System.Threading.Tasks.Task{Microsoft.Azure.Graph.RBAC.Models.ApplicationListResult}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<ApplicationListResult>
  fullName: System.Threading.Tasks.Task<Microsoft.Azure.Graph.RBAC.Models.ApplicationListResult>
  fullname.vb: System.Threading.Tasks.Task(Of Microsoft.Azure.Graph.RBAC.Models.ApplicationListResult)
  name.vb: Task(Of ApplicationListResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Graph.RBAC.Models.ApplicationListResult
    name: ApplicationListResult
    fullName: Microsoft.Azure.Graph.RBAC.Models.ApplicationListResult
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Graph.RBAC.Models.ApplicationListResult
    name: ApplicationListResult
    fullName: Microsoft.Azure.Graph.RBAC.Models.ApplicationListResult
  - name: )
    fullName: )
