items:
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping
  commentId: T:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping
  id: WebSiteGetConfigurationResponse.HandlerMapping
  parent: Microsoft.WindowsAzure.Management.WebSites.Models
  children:
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.#ctor
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.Arguments
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.Extension
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.ScriptProcessor
  langs:
  - csharp
  - vb
  name: WebSiteGetConfigurationResponse.HandlerMapping
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping
  type: Class
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: HandlerMapping
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResponse.cs
    startLine: 466
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nSpecifies a custom executable program for handling requests for\r\nspecific file name extensions.\r\n"
  example: []
  syntax:
    content: public class HandlerMapping
    content.vb: Public Class HandlerMapping
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.Arguments
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.Arguments
  id: Arguments
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping
  langs:
  - csharp
  - vb
  name: Arguments
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.Arguments
  type: Property
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Arguments
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResponse.cs
    startLine: 476
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. A string that contains optional arguments for the\r\nscript processor specified by the\r\nSiteConfig.HandlerMappings.HandlerMapping.ScriptProcessor\r\nelement.\r\n"
  example: []
  syntax:
    content: >-
      public string Arguments

      {

          get;

          set;

      }
    content.vb: Public Property Arguments As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.Extension
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.Extension
  id: Extension
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping
  langs:
  - csharp
  - vb
  name: Extension
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.Extension
  type: Property
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Extension
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResponse.cs
    startLine: 489
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. A string that specifies the extension of the file\r\ntype that the script processor will handle (for example,\r\n*.php).\r\n"
  example: []
  syntax:
    content: >-
      public string Extension

      {

          get;

          set;

      }
    content.vb: Public Property Extension As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.ScriptProcessor
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.ScriptProcessor
  id: ScriptProcessor
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping
  langs:
  - csharp
  - vb
  name: ScriptProcessor
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.ScriptProcessor
  type: Property
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ScriptProcessor
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResponse.cs
    startLine: 502
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. The absolute path to the location of the executable\r\nfile that will handle the files specified in the\r\nSiteConfig.HandlerMappings.HandlerMapping.Extension element.\r\n"
  example: []
  syntax:
    content: >-
      public string ScriptProcessor

      {

          get;

          set;

      }
    content.vb: Public Property ScriptProcessor As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping
  langs:
  - csharp
  - vb
  name: HandlerMapping()
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetConfigurationResponse.HandlerMapping.HandlerMapping()
  type: Constructor
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResponse.cs
    startLine: 511
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nInitializes a new instance of the HandlerMapping class.\r\n"
  example: []
  syntax:
    content: public HandlerMapping()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.WebSites.Models
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
