items:
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames
  commentId: T:Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames
  id: SlotConfigNames
  parent: Microsoft.WindowsAzure.Management.WebSites.Models
  children:
  - Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.#ctor
  - Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.AppSettingNames
  - Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.ConnectionStringNames
  langs:
  - csharp
  - vb
  name: SlotConfigNames
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames
  type: Class
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNames.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: SlotConfigNames
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNames.cs
    startLine: 33
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nA standard service response including an HTTP status code and request\r\nID.\r\n"
  example: []
  syntax:
    content: 'public class SlotConfigNames : AzureOperationResponse'
    content.vb: >-
      Public Class SlotConfigNames

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.AppSettingNames
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.AppSettingNames
  id: AppSettingNames
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames
  langs:
  - csharp
  - vb
  name: AppSettingNames
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.AppSettingNames
  type: Property
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNames.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: AppSettingNames
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNames.cs
    startLine: 44
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. One or more string elements that list the name of the app\r\nsetting that will not be moved durig site swap. For example, if\r\nslot named staging has setting EnableVerboseLogging=1, it\r\nshouldn't be moved when swapped with production slot but should\r\ntake the current value from production.\r\n"
  example: []
  syntax:
    content: >-
      public IList<string> AppSettingNames

      {

          get;

          set;

      }
    content.vb: Public Property AppSettingNames As IList(Of String)
    parameters: []
    return:
      type: System.Collections.Generic.IList{System.String}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.ConnectionStringNames
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.ConnectionStringNames
  id: ConnectionStringNames
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames
  langs:
  - csharp
  - vb
  name: ConnectionStringNames
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.ConnectionStringNames
  type: Property
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNames.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ConnectionStringNames
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNames.cs
    startLine: 60
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. One or more string elements that list the name of the\r\nconnection string setting that will not be moved durig site swap.\r\nFor example, if slot named staging has connection UsersDatabase\r\nthat points to staging test database, it shouldn't be moved when\r\nswapped with production slot but should take the current value\r\nfrom production.\r\n"
  example: []
  syntax:
    content: >-
      public IList<string> ConnectionStringNames

      {

          get;

          set;

      }
    content.vb: Public Property ConnectionStringNames As IList(Of String)
    parameters: []
    return:
      type: System.Collections.Generic.IList{System.String}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames
  langs:
  - csharp
  - vb
  name: SlotConfigNames()
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.SlotConfigNames.SlotConfigNames()
  type: Constructor
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNames.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNames.cs
    startLine: 69
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nInitializes a new instance of the SlotConfigNames class.\r\n"
  example: []
  syntax:
    content: public SlotConfigNames()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.WebSites.Models
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.IList{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<String>
  fullName: System.Collections.Generic.IList<System.String>
  fullname.vb: System.Collections.Generic.IList(Of System.String)
  name.vb: IList(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
