items:
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters
  id: DeploymentWalkUpgradeDomainParameters
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  children:
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.#ctor
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.#ctor(System.Int32)
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.UpgradeDomain
  langs:
  - csharp
  - vb
  name: DeploymentWalkUpgradeDomainParameters
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters
  type: Class
  source:
    remote:
      path: src/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentWalkUpgradeDomainParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: DeploymentWalkUpgradeDomainParameters
    path: src/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentWalkUpgradeDomainParameters.cs
    startLine: 29
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nParameters supplied to the Walk Upgrade Domain operation.\r\n"
  example: []
  syntax:
    content: public class DeploymentWalkUpgradeDomainParameters
    content.vb: Public Class DeploymentWalkUpgradeDomainParameters
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.UpgradeDomain
  commentId: P:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.UpgradeDomain
  id: UpgradeDomain
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters
  langs:
  - csharp
  - vb
  name: UpgradeDomain
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.UpgradeDomain
  type: Property
  source:
    remote:
      path: src/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentWalkUpgradeDomainParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: UpgradeDomain
    path: src/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentWalkUpgradeDomainParameters.cs
    startLine: 39
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nRequired. An integer value that identifies the update domain to\r\nupdate. Update domains are identified with a zero-based index: the\r\nfirst update domain has an ID of 0, the second has an ID of 1, and\r\nso on.\r\n"
  example: []
  syntax:
    content: >-
      public int UpgradeDomain

      {

          get;

          set;

      }
    content.vb: Public Property UpgradeDomain As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters
  langs:
  - csharp
  - vb
  name: DeploymentWalkUpgradeDomainParameters()
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.DeploymentWalkUpgradeDomainParameters()
  type: Constructor
  source:
    remote:
      path: src/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentWalkUpgradeDomainParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentWalkUpgradeDomainParameters.cs
    startLine: 49
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nInitializes a new instance of the\r\nDeploymentWalkUpgradeDomainParameters class.\r\n"
  example: []
  syntax:
    content: public DeploymentWalkUpgradeDomainParameters()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.#ctor(System.Int32)
  commentId: M:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.#ctor(System.Int32)
  id: '#ctor(System.Int32)'
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters
  langs:
  - csharp
  - vb
  name: DeploymentWalkUpgradeDomainParameters(Int32)
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentWalkUpgradeDomainParameters.DeploymentWalkUpgradeDomainParameters(System.Int32)
  type: Constructor
  source:
    remote:
      path: src/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentWalkUpgradeDomainParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentWalkUpgradeDomainParameters.cs
    startLine: 58
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nInitializes a new instance of the\r\nDeploymentWalkUpgradeDomainParameters class with required\r\narguments.\r\n"
  example: []
  syntax:
    content: public DeploymentWalkUpgradeDomainParameters(int upgradeDomain)
    content.vb: Public Sub New(upgradeDomain As Integer)
    parameters:
    - id: upgradeDomain
      type: System.Int32
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Compute.Models
  fullName: Microsoft.WindowsAzure.Management.Compute.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  fullName: System.Int32
