items:
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  commentId: T:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  id: WebSiteGetBackupConfigurationResponse
  parent: Microsoft.WindowsAzure.Management.WebSites.Models
  children:
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.#ctor
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.BackupSchedule
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Databases
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Enabled
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Name
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.StorageAccountUrl
  langs:
  - csharp
  - vb
  name: WebSiteGetBackupConfigurationResponse
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  type: Class
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: WebSiteGetBackupConfigurationResponse
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
    startLine: 33
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nScheduled backup definition.\r\n"
  example: []
  syntax:
    content: 'public class WebSiteGetBackupConfigurationResponse : AzureOperationResponse'
    content.vb: >-
      Public Class WebSiteGetBackupConfigurationResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.BackupSchedule
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.BackupSchedule
  id: BackupSchedule
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  langs:
  - csharp
  - vb
  name: BackupSchedule
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.BackupSchedule
  type: Property
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: BackupSchedule
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
    startLine: 41
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. Schedule - defines how often should be the backup\r\nperformed.\r\n"
  example: []
  syntax:
    content: >-
      public BackupSchedule BackupSchedule

      {

          get;

          set;

      }
    content.vb: Public Property BackupSchedule As BackupSchedule
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.WebSites.Models.BackupSchedule
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Databases
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Databases
  id: Databases
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  langs:
  - csharp
  - vb
  name: Databases
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Databases
  type: Property
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Databases
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
    startLine: 52
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. Database settings for backup.\r\n"
  example: []
  syntax:
    content: >-
      public IList<DatabaseBackupSetting> Databases

      {

          get;

          set;

      }
    content.vb: Public Property Databases As IList(Of DatabaseBackupSetting)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.WindowsAzure.Management.WebSites.Models.DatabaseBackupSetting}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Enabled
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Enabled
  id: Enabled
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  langs:
  - csharp
  - vb
  name: Enabled
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Enabled
  type: Property
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Enabled
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
    startLine: 64
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. True if this schedule is enabled and periodically\r\nexecuted; otherwise, false.\r\n"
  example: []
  syntax:
    content: >-
      public bool ? Enabled

      {

          get;

          set;

      }
    content.vb: Public Property Enabled As Boolean?
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Name
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Name
  id: Name
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.Name
  type: Property
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Name
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
    startLine: 75
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. Name of a backup.\r\n"
  example: []
  syntax:
    content: >-
      public string Name

      {

          get;

          set;

      }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.StorageAccountUrl
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.StorageAccountUrl
  id: StorageAccountUrl
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  langs:
  - csharp
  - vb
  name: StorageAccountUrl
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.StorageAccountUrl
  type: Property
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: StorageAccountUrl
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
    startLine: 87
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  syntax:
    content: >-
      public string StorageAccountUrl

      {

          get;

          set;

      }
    content.vb: Public Property StorageAccountUrl As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  langs:
  - csharp
  - vb
  name: WebSiteGetBackupConfigurationResponse()
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.WebSiteGetBackupConfigurationResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
    startLine: 97
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nInitializes a new instance of the\r\nWebSiteGetBackupConfigurationResponse class.\r\n"
  example: []
  syntax:
    content: public WebSiteGetBackupConfigurationResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.WebSites.Models
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.BackupSchedule
  parent: Microsoft.WindowsAzure.Management.WebSites.Models
  isExternal: false
  name: BackupSchedule
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.BackupSchedule
- uid: System.Collections.Generic.IList{Microsoft.WindowsAzure.Management.WebSites.Models.DatabaseBackupSetting}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<DatabaseBackupSetting>
  fullName: System.Collections.Generic.IList<Microsoft.WindowsAzure.Management.WebSites.Models.DatabaseBackupSetting>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.WindowsAzure.Management.WebSites.Models.DatabaseBackupSetting)
  name.vb: IList(Of DatabaseBackupSetting)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.WindowsAzure.Management.WebSites.Models.DatabaseBackupSetting
    name: DatabaseBackupSetting
    fullName: Microsoft.WindowsAzure.Management.WebSites.Models.DatabaseBackupSetting
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.WindowsAzure.Management.WebSites.Models.DatabaseBackupSetting
    name: DatabaseBackupSetting
    fullName: Microsoft.WindowsAzure.Management.WebSites.Models.DatabaseBackupSetting
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  fullname.vb: System.Nullable(Of System.Boolean)
  name.vb: Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
