items:
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  commentId: T:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  id: OperationStatusValues
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  children:
  - Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Canceled
  - Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Failed
  - Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.InProgress
  - Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Invalid
  - Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Succeeded
  langs:
  - csharp
  - vb
  name: OperationStatusValues
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: OperationStatusValues
    path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  summary: "\r\nThe enum for all supported type of operation status.\r\n"
  example: []
  syntax:
    content: public class OperationStatusValues
    content.vb: Public Class OperationStatusValues
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Invalid
  commentId: F:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Invalid
  id: Invalid
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  langs:
  - csharp
  - vb
  name: Invalid
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Invalid
  type: Field
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Invalid
    path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
    startLine: 34
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  summary: "\r\nInvalid Status of OperationStatus.\r\n"
  example: []
  syntax:
    content: public const string Invalid = "Invalid"
    content.vb: Public Const Invalid As String = "Invalid"
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.InProgress
  commentId: F:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.InProgress
  id: InProgress
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  langs:
  - csharp
  - vb
  name: InProgress
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.InProgress
  type: Field
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: InProgress
    path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  summary: "\r\nInProgress Status of OperationStatus.\r\n"
  example: []
  syntax:
    content: public const string InProgress = "InProgress"
    content.vb: Public Const InProgress As String = "InProgress"
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Succeeded
  commentId: F:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Succeeded
  id: Succeeded
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  langs:
  - csharp
  - vb
  name: Succeeded
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Succeeded
  type: Field
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Succeeded
    path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
    startLine: 44
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  summary: "\r\nSucceeded Status of OperationStatus.\r\n"
  example: []
  syntax:
    content: public const string Succeeded = "Succeeded"
    content.vb: Public Const Succeeded As String = "Succeeded"
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Failed
  commentId: F:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Failed
  id: Failed
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  langs:
  - csharp
  - vb
  name: Failed
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Failed
  type: Field
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Failed
    path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  summary: "\r\nFailed Status of OperationStatus.\r\n"
  example: []
  syntax:
    content: public const string Failed = "Failed"
    content.vb: Public Const Failed As String = "Failed"
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Canceled
  commentId: F:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Canceled
  id: Canceled
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  langs:
  - csharp
  - vb
  name: Canceled
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Canceled
  type: Field
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Canceled
    path: src/src/ResourceManagement/RecoveryServices.Backup/RecoveryServicesBackupManagement/Generated/Models/OperationStatusValues.cs
    startLine: 54
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  summary: "\r\nCanceled Status of OperationStatus.\r\n"
  example: []
  syntax:
    content: public const string Canceled = "Canceled"
    content.vb: Public Const Canceled As String = "Canceled"
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  isExternal: false
  name: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
