items:
- uid: Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  commentId: T:Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  id: WebSiteGetBackupConfigurationResponse
  parent: Microsoft.Azure.Management.WebSites.Models
  children:
  - Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.#ctor
  - Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.BackupSchedule
  langs:
  - csharp
  - vb
  name: WebSiteGetBackupConfigurationResponse
  fullName: Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: WebSiteGetBackupConfigurationResponse
    path: src/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nScheduled backup definition.\r\n"
  example: []
  syntax:
    content: 'public class WebSiteGetBackupConfigurationResponse : AzureOperationResponse'
    content.vb: >-
      Public Class WebSiteGetBackupConfigurationResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.BackupSchedule
  commentId: P:Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.BackupSchedule
  id: BackupSchedule
  parent: Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  langs:
  - csharp
  - vb
  name: BackupSchedule
  fullName: Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.BackupSchedule
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: BackupSchedule
    path: src/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nOptional. Backups schedule for a site.\r\n"
  example: []
  syntax:
    content: >-
      public BackupScheduleRequestEnvelope BackupSchedule

      {

          get;

          set;

      }
    content.vb: Public Property BackupSchedule As BackupScheduleRequestEnvelope
    parameters: []
    return:
      type: Microsoft.Azure.Management.WebSites.Models.BackupScheduleRequestEnvelope
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.#ctor
  commentId: M:Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse
  langs:
  - csharp
  - vb
  name: WebSiteGetBackupConfigurationResponse()
  fullName: Microsoft.Azure.Management.WebSites.Models.WebSiteGetBackupConfigurationResponse.WebSiteGetBackupConfigurationResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetBackupConfigurationResponse.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nInitializes a new instance of the\r\nWebSiteGetBackupConfigurationResponse class.\r\n"
  example: []
  syntax:
    content: public WebSiteGetBackupConfigurationResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.Azure.Management.WebSites.Models
  fullName: Microsoft.Azure.Management.WebSites.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.WebSites.Models.BackupScheduleRequestEnvelope
  parent: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: BackupScheduleRequestEnvelope
  fullName: Microsoft.Azure.Management.WebSites.Models.BackupScheduleRequestEnvelope
