items:
- uid: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse
  commentId: T:Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse
  id: ListApplicationsResponse
  parent: Microsoft.Azure.Management.Batch.Models
  children:
  - Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.#ctor
  - Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.Application})
  - Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.Applications
  - Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.NextLink
  langs:
  - csharp
  - vb
  name: ListApplicationsResponse
  fullName: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ListApplicationsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ListApplicationsResponse
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ListApplicationsResponse.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nResponse to an ApplicationOperations.ListApplications request.\r\n"
  example: []
  syntax:
    content: 'public class ListApplicationsResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ListApplicationsResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.Applications
  commentId: P:Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.Applications
  id: Applications
  parent: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse
  langs:
  - csharp
  - vb
  name: Applications
  fullName: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.Applications
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ListApplicationsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Applications
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ListApplicationsResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nRequired. Gets or sets the list of applications.\r\n"
  example: []
  syntax:
    content: >-
      public IList<Application> Applications

      {

          get;

          set;

      }
    content.vb: Public Property Applications As IList(Of Application)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.Application}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.NextLink
  commentId: P:Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.NextLink
  id: NextLink
  parent: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse
  langs:
  - csharp
  - vb
  name: NextLink
  fullName: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.NextLink
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ListApplicationsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: NextLink
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ListApplicationsResponse.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nOptional. Gets or sets the URL to get the next set of results.\r\n"
  example: []
  syntax:
    content: >-
      public string NextLink

      {

          get;

          set;

      }
    content.vb: Public Property NextLink As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse
  langs:
  - csharp
  - vb
  name: ListApplicationsResponse()
  fullName: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.ListApplicationsResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ListApplicationsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ListApplicationsResponse.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nInitializes a new instance of the ListApplicationsResponse class.\r\n"
  example: []
  syntax:
    content: public ListApplicationsResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.Application})
  commentId: M:Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.Application})
  id: '#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.Application})'
  parent: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse
  langs:
  - csharp
  - vb
  name: ListApplicationsResponse(IList<Application>)
  fullName: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.ListApplicationsResponse(System.Collections.Generic.IList<Microsoft.Azure.Management.Batch.Models.Application>)
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ListApplicationsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ListApplicationsResponse.cs
    startLine: 67
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nInitializes a new instance of the ListApplicationsResponse class\r\nwith required arguments.\r\n"
  example: []
  syntax:
    content: public ListApplicationsResponse(IList<Application> applications)
    content.vb: Public Sub New(applications As IList(Of Application))
    parameters:
    - id: applications
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.Application}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Batch.Models.ListApplicationsResponse.ListApplicationsResponse(System.Collections.Generic.IList(Of Microsoft.Azure.Management.Batch.Models.Application))
  name.vb: ListApplicationsResponse(IList(Of Application))
references:
- uid: Microsoft.Azure.Management.Batch.Models
  isExternal: false
  name: Microsoft.Azure.Management.Batch.Models
  fullName: Microsoft.Azure.Management.Batch.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.Application}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<Application>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.Batch.Models.Application>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.Batch.Models.Application)
  name.vb: IList(Of Application)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Batch.Models.Application
    name: Application
    fullName: Microsoft.Azure.Management.Batch.Models.Application
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Batch.Models.Application
    name: Application
    fullName: Microsoft.Azure.Management.Batch.Models.Application
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
