items:
- uid: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse
  commentId: T:Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse
  id: GetApplicationPackageResponse
  parent: Microsoft.Azure.Management.Batch.Models
  children:
  - Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.#ctor
  - Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Format
  - Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Id
  - Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.LastActivationTime
  - Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.State
  - Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.StorageUrl
  - Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.StorageUrlExpiry
  - Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Version
  langs:
  - csharp
  - vb
  name: GetApplicationPackageResponse
  fullName: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: GetApplicationPackageResponse
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nResponse to an ApplicationOperations.GetApplicationPackage request.\r\n"
  example: []
  syntax:
    content: 'public class GetApplicationPackageResponse : AzureOperationResponse'
    content.vb: >-
      Public Class GetApplicationPackageResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Format
  commentId: P:Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Format
  id: Format
  parent: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse
  langs:
  - csharp
  - vb
  name: Format
  fullName: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Format
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Format
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nOptional. Gets or sets the format of the application package, if\r\nknown.\r\n"
  example: []
  syntax:
    content: >-
      public string Format

      {

          get;

          set;

      }
    content.vb: Public Property Format As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Id
  commentId: P:Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Id
  id: Id
  parent: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse
  langs:
  - csharp
  - vb
  name: Id
  fullName: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Id
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Id
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nRequired. Gets or sets the id of the application.\r\n"
  example: []
  syntax:
    content: >-
      public string Id

      {

          get;

          set;

      }
    content.vb: Public Property Id As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.LastActivationTime
  commentId: P:Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.LastActivationTime
  id: LastActivationTime
  parent: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse
  langs:
  - csharp
  - vb
  name: LastActivationTime
  fullName: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.LastActivationTime
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: LastActivationTime
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
    startLine: 62
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nOptional. Gets or sets the time at which the package was last\r\nactivated, if the package is active.\r\n"
  example: []
  syntax:
    content: >-
      public DateTime? LastActivationTime

      {

          get;

          set;

      }
    content.vb: Public Property LastActivationTime As Date?
    parameters: []
    return:
      type: System.Nullable{System.DateTime}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.State
  commentId: P:Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.State
  id: State
  parent: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse
  langs:
  - csharp
  - vb
  name: State
  fullName: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.State
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: State
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
    startLine: 73
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nRequired. Gets or sets the current state of the application package.\r\n"
  example: []
  syntax:
    content: >-
      public PackageState State

      {

          get;

          set;

      }
    content.vb: Public Property State As PackageState
    parameters: []
    return:
      type: Microsoft.Azure.Management.Batch.Models.PackageState
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.StorageUrl
  commentId: P:Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.StorageUrl
  id: StorageUrl
  parent: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse
  langs:
  - csharp
  - vb
  name: StorageUrl
  fullName: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.StorageUrl
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: StorageUrl
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
    startLine: 85
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nRequired. Gets or sets the URL at which the application package\r\nblob is stored.\r\n"
  example: []
  syntax:
    content: >-
      public string StorageUrl

      {

          get;

          set;

      }
    content.vb: Public Property StorageUrl As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.StorageUrlExpiry
  commentId: P:Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.StorageUrlExpiry
  id: StorageUrlExpiry
  parent: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse
  langs:
  - csharp
  - vb
  name: StorageUrlExpiry
  fullName: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.StorageUrlExpiry
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: StorageUrlExpiry
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
    startLine: 97
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nRequired. Gets or sets the UTC time at which the storage URL will\r\nexpire.\r\n"
  example: []
  syntax:
    content: >-
      public DateTime StorageUrlExpiry

      {

          get;

          set;

      }
    content.vb: Public Property StorageUrlExpiry As Date
    parameters: []
    return:
      type: System.DateTime
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Version
  commentId: P:Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Version
  id: Version
  parent: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse
  langs:
  - csharp
  - vb
  name: Version
  fullName: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.Version
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Version
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
    startLine: 108
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nRequired. Gets or sets the version of the application package.\r\n"
  example: []
  syntax:
    content: >-
      public string Version

      {

          get;

          set;

      }
    content.vb: Public Property Version As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse
  langs:
  - csharp
  - vb
  name: GetApplicationPackageResponse()
  fullName: Microsoft.Azure.Management.Batch.Models.GetApplicationPackageResponse.GetApplicationPackageResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/GetApplicationPackageResponse.cs
    startLine: 118
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nInitializes a new instance of the GetApplicationPackageResponse\r\nclass.\r\n"
  example: []
  syntax:
    content: public GetApplicationPackageResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Batch.Models
  isExternal: false
  name: Microsoft.Azure.Management.Batch.Models
  fullName: Microsoft.Azure.Management.Batch.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Nullable{System.DateTime}
  parent: System
  definition: System.Nullable`1
  name: Nullable<DateTime>
  fullName: System.Nullable<System.DateTime>
  fullname.vb: System.Nullable(Of System.DateTime)
  name.vb: Nullable(Of DateTime)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.DateTime
    name: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.DateTime
    name: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Batch.Models.PackageState
  parent: Microsoft.Azure.Management.Batch.Models
  isExternal: false
  name: PackageState
  fullName: Microsoft.Azure.Management.Batch.Models.PackageState
- uid: System.DateTime
  parent: System
  isExternal: true
  name: DateTime
  fullName: System.DateTime
