items:
- uid: Microsoft.Azure.Management.Batch.Models.AddApplicationResponse
  commentId: T:Microsoft.Azure.Management.Batch.Models.AddApplicationResponse
  id: AddApplicationResponse
  parent: Microsoft.Azure.Management.Batch.Models
  children:
  - Microsoft.Azure.Management.Batch.Models.AddApplicationResponse.#ctor
  - Microsoft.Azure.Management.Batch.Models.AddApplicationResponse.Application
  langs:
  - csharp
  - vb
  name: AddApplicationResponse
  fullName: Microsoft.Azure.Management.Batch.Models.AddApplicationResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/AddApplicationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: AddApplicationResponse
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/AddApplicationResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nResponse to an ApplicationOperations.AddApplicationResponse request.\r\n"
  example: []
  syntax:
    content: 'public class AddApplicationResponse : AzureOperationResponse'
    content.vb: >-
      Public Class AddApplicationResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Batch.Models.AddApplicationResponse.Application
  commentId: P:Microsoft.Azure.Management.Batch.Models.AddApplicationResponse.Application
  id: Application
  parent: Microsoft.Azure.Management.Batch.Models.AddApplicationResponse
  langs:
  - csharp
  - vb
  name: Application
  fullName: Microsoft.Azure.Management.Batch.Models.AddApplicationResponse.Application
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/AddApplicationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Application
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/AddApplicationResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nOptional. Gets or sets the information about the application.\r\n"
  example: []
  syntax:
    content: >-
      public Application Application

      {

          get;

          set;

      }
    content.vb: Public Property Application As Application
    parameters: []
    return:
      type: Microsoft.Azure.Management.Batch.Models.Application
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.AddApplicationResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Batch.Models.AddApplicationResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Batch.Models.AddApplicationResponse
  langs:
  - csharp
  - vb
  name: AddApplicationResponse()
  fullName: Microsoft.Azure.Management.Batch.Models.AddApplicationResponse.AddApplicationResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/AddApplicationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/AddApplicationResponse.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nInitializes a new instance of the AddApplicationResponse class.\r\n"
  example: []
  syntax:
    content: public AddApplicationResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Batch.Models
  isExternal: false
  name: Microsoft.Azure.Management.Batch.Models
  fullName: Microsoft.Azure.Management.Batch.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Batch.Models.Application
  parent: Microsoft.Azure.Management.Batch.Models
  isExternal: false
  name: Application
  fullName: Microsoft.Azure.Management.Batch.Models.Application
