items:
- uid: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
  commentId: T:Microsoft.Azure.Management.Batch.Models.ApplicationPackage
  id: ApplicationPackage
  parent: Microsoft.Azure.Management.Batch.Models
  children:
  - Microsoft.Azure.Management.Batch.Models.ApplicationPackage.#ctor
  - Microsoft.Azure.Management.Batch.Models.ApplicationPackage.#ctor(Microsoft.Azure.Management.Batch.Models.PackageState)
  - Microsoft.Azure.Management.Batch.Models.ApplicationPackage.Format
  - Microsoft.Azure.Management.Batch.Models.ApplicationPackage.LastActivationTime
  - Microsoft.Azure.Management.Batch.Models.ApplicationPackage.State
  - Microsoft.Azure.Management.Batch.Models.ApplicationPackage.Version
  langs:
  - csharp
  - vb
  name: ApplicationPackage
  fullName: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ApplicationPackage
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nContains information about an application package.\r\n"
  example: []
  syntax:
    content: public class ApplicationPackage
    content.vb: Public Class ApplicationPackage
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.Format
  commentId: P:Microsoft.Azure.Management.Batch.Models.ApplicationPackage.Format
  id: Format
  parent: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
  langs:
  - csharp
  - vb
  name: Format
  fullName: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.Format
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Format
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nOptional. Gets or sets the format of the application package, if\r\nknown.\r\n"
  example: []
  syntax:
    content: >-
      public string Format

      {

          get;

          set;

      }
    content.vb: Public Property Format As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.LastActivationTime
  commentId: P:Microsoft.Azure.Management.Batch.Models.ApplicationPackage.LastActivationTime
  id: LastActivationTime
  parent: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
  langs:
  - csharp
  - vb
  name: LastActivationTime
  fullName: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.LastActivationTime
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: LastActivationTime
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nOptional. Gets or sets the time at which the package was last\r\nactivated, if the package is active.\r\n"
  example: []
  syntax:
    content: >-
      public DateTime? LastActivationTime

      {

          get;

          set;

      }
    content.vb: Public Property LastActivationTime As Date?
    parameters: []
    return:
      type: System.Nullable{System.DateTime}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.State
  commentId: P:Microsoft.Azure.Management.Batch.Models.ApplicationPackage.State
  id: State
  parent: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
  langs:
  - csharp
  - vb
  name: State
  fullName: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.State
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: State
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
    startLine: 61
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nRequired. Gets or sets the current state of the application package.\r\n"
  example: []
  syntax:
    content: >-
      public PackageState State

      {

          get;

          set;

      }
    content.vb: Public Property State As PackageState
    parameters: []
    return:
      type: Microsoft.Azure.Management.Batch.Models.PackageState
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.Version
  commentId: P:Microsoft.Azure.Management.Batch.Models.ApplicationPackage.Version
  id: Version
  parent: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
  langs:
  - csharp
  - vb
  name: Version
  fullName: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.Version
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Version
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
    startLine: 72
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nOptional. Gets or sets the version of the application package.\r\n"
  example: []
  syntax:
    content: >-
      public string Version

      {

          get;

          set;

      }
    content.vb: Public Property Version As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.#ctor
  commentId: M:Microsoft.Azure.Management.Batch.Models.ApplicationPackage.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
  langs:
  - csharp
  - vb
  name: ApplicationPackage()
  fullName: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.ApplicationPackage()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
    startLine: 81
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nInitializes a new instance of the ApplicationPackage class.\r\n"
  example: []
  syntax:
    content: public ApplicationPackage()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.#ctor(Microsoft.Azure.Management.Batch.Models.PackageState)
  commentId: M:Microsoft.Azure.Management.Batch.Models.ApplicationPackage.#ctor(Microsoft.Azure.Management.Batch.Models.PackageState)
  id: '#ctor(Microsoft.Azure.Management.Batch.Models.PackageState)'
  parent: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
  langs:
  - csharp
  - vb
  name: ApplicationPackage(PackageState)
  fullName: Microsoft.Azure.Management.Batch.Models.ApplicationPackage.ApplicationPackage(Microsoft.Azure.Management.Batch.Models.PackageState)
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ApplicationPackage.cs
    startLine: 89
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nInitializes a new instance of the ApplicationPackage class with\r\nrequired arguments.\r\n"
  example: []
  syntax:
    content: public ApplicationPackage(PackageState state)
    content.vb: Public Sub New(state As PackageState)
    parameters:
    - id: state
      type: Microsoft.Azure.Management.Batch.Models.PackageState
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Batch.Models
  isExternal: false
  name: Microsoft.Azure.Management.Batch.Models
  fullName: Microsoft.Azure.Management.Batch.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Nullable{System.DateTime}
  parent: System
  definition: System.Nullable`1
  name: Nullable<DateTime>
  fullName: System.Nullable<System.DateTime>
  fullname.vb: System.Nullable(Of System.DateTime)
  name.vb: Nullable(Of DateTime)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.DateTime
    name: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.DateTime
    name: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Batch.Models.PackageState
  parent: Microsoft.Azure.Management.Batch.Models
  isExternal: false
  name: PackageState
  fullName: Microsoft.Azure.Management.Batch.Models.PackageState
