items:
- uid: Microsoft.Azure.Management.Batch.Models.Application
  commentId: T:Microsoft.Azure.Management.Batch.Models.Application
  id: Application
  parent: Microsoft.Azure.Management.Batch.Models
  children:
  - Microsoft.Azure.Management.Batch.Models.Application.#ctor
  - Microsoft.Azure.Management.Batch.Models.Application.#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationPackage},System.Boolean)
  - Microsoft.Azure.Management.Batch.Models.Application.AllowUpdates
  - Microsoft.Azure.Management.Batch.Models.Application.ApplicationPackages
  - Microsoft.Azure.Management.Batch.Models.Application.DefaultVersion
  - Microsoft.Azure.Management.Batch.Models.Application.DisplayName
  - Microsoft.Azure.Management.Batch.Models.Application.Id
  langs:
  - csharp
  - vb
  name: Application
  fullName: Microsoft.Azure.Management.Batch.Models.Application
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Application
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nContains information about an application in a Batch account.\r\n"
  example: []
  syntax:
    content: public class Application
    content.vb: Public Class Application
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Batch.Models.Application.AllowUpdates
  commentId: P:Microsoft.Azure.Management.Batch.Models.Application.AllowUpdates
  id: AllowUpdates
  parent: Microsoft.Azure.Management.Batch.Models.Application
  langs:
  - csharp
  - vb
  name: AllowUpdates
  fullName: Microsoft.Azure.Management.Batch.Models.Application.AllowUpdates
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: AllowUpdates
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nRequired. Gets or sets whether packages within the application may\r\nbe overwritten using the same version string.\r\n"
  example: []
  syntax:
    content: >-
      public bool AllowUpdates

      {

          get;

          set;

      }
    content.vb: Public Property AllowUpdates As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.Application.ApplicationPackages
  commentId: P:Microsoft.Azure.Management.Batch.Models.Application.ApplicationPackages
  id: ApplicationPackages
  parent: Microsoft.Azure.Management.Batch.Models.Application
  langs:
  - csharp
  - vb
  name: ApplicationPackages
  fullName: Microsoft.Azure.Management.Batch.Models.Application.ApplicationPackages
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ApplicationPackages
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nRequired. Gets or sets the list of packages under this application.\r\n"
  example: []
  syntax:
    content: >-
      public IList<ApplicationPackage> ApplicationPackages

      {

          get;

          set;

      }
    content.vb: Public Property ApplicationPackages As IList(Of ApplicationPackage)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationPackage}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.Application.DefaultVersion
  commentId: P:Microsoft.Azure.Management.Batch.Models.Application.DefaultVersion
  id: DefaultVersion
  parent: Microsoft.Azure.Management.Batch.Models.Application
  langs:
  - csharp
  - vb
  name: DefaultVersion
  fullName: Microsoft.Azure.Management.Batch.Models.Application.DefaultVersion
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: DefaultVersion
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
    startLine: 62
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nOptional. Gets or sets which package to use if a client requests\r\nthe application but does not specify a version.\r\n"
  example: []
  syntax:
    content: >-
      public string DefaultVersion

      {

          get;

          set;

      }
    content.vb: Public Property DefaultVersion As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.Application.DisplayName
  commentId: P:Microsoft.Azure.Management.Batch.Models.Application.DisplayName
  id: DisplayName
  parent: Microsoft.Azure.Management.Batch.Models.Application
  langs:
  - csharp
  - vb
  name: DisplayName
  fullName: Microsoft.Azure.Management.Batch.Models.Application.DisplayName
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: DisplayName
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
    startLine: 73
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nOptional. Gets or sets the display name for the application.\r\n"
  example: []
  syntax:
    content: >-
      public string DisplayName

      {

          get;

          set;

      }
    content.vb: Public Property DisplayName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.Application.Id
  commentId: P:Microsoft.Azure.Management.Batch.Models.Application.Id
  id: Id
  parent: Microsoft.Azure.Management.Batch.Models.Application
  langs:
  - csharp
  - vb
  name: Id
  fullName: Microsoft.Azure.Management.Batch.Models.Application.Id
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Id
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
    startLine: 85
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nRequired. Gets or sets a string that uniquely identifies the\r\napplication within the account.\r\n"
  example: []
  syntax:
    content: >-
      public string Id

      {

          get;

          set;

      }
    content.vb: Public Property Id As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.Application.#ctor
  commentId: M:Microsoft.Azure.Management.Batch.Models.Application.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Batch.Models.Application
  langs:
  - csharp
  - vb
  name: Application()
  fullName: Microsoft.Azure.Management.Batch.Models.Application.Application()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
    startLine: 94
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nInitializes a new instance of the Application class.\r\n"
  example: []
  syntax:
    content: public Application()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.Application.#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationPackage},System.Boolean)
  commentId: M:Microsoft.Azure.Management.Batch.Models.Application.#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationPackage},System.Boolean)
  id: '#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationPackage},System.Boolean)'
  parent: Microsoft.Azure.Management.Batch.Models.Application
  langs:
  - csharp
  - vb
  name: Application(String, IList<ApplicationPackage>, Boolean)
  fullName: Microsoft.Azure.Management.Batch.Models.Application.Application(System.String, System.Collections.Generic.IList<Microsoft.Azure.Management.Batch.Models.ApplicationPackage>, System.Boolean)
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/Application.cs
    startLine: 102
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nInitializes a new instance of the Application class with required\r\narguments.\r\n"
  example: []
  syntax:
    content: public Application(string id, IList<ApplicationPackage> applicationPackages, bool allowUpdates)
    content.vb: Public Sub New(id As String, applicationPackages As IList(Of ApplicationPackage), allowUpdates As Boolean)
    parameters:
    - id: id
      type: System.String
    - id: applicationPackages
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationPackage}
    - id: allowUpdates
      type: System.Boolean
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Batch.Models.Application.Application(System.String, System.Collections.Generic.IList(Of Microsoft.Azure.Management.Batch.Models.ApplicationPackage), System.Boolean)
  name.vb: Application(String, IList(Of ApplicationPackage), Boolean)
references:
- uid: Microsoft.Azure.Management.Batch.Models
  isExternal: false
  name: Microsoft.Azure.Management.Batch.Models
  fullName: Microsoft.Azure.Management.Batch.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationPackage}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<ApplicationPackage>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.Batch.Models.ApplicationPackage>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.Batch.Models.ApplicationPackage)
  name.vb: IList(Of ApplicationPackage)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
    name: ApplicationPackage
    fullName: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
    name: ApplicationPackage
    fullName: Microsoft.Azure.Management.Batch.Models.ApplicationPackage
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
