items:
- uid: Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters
  commentId: T:Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters
  id: ActivateApplicationPackageParameters
  parent: Microsoft.Azure.Management.Batch.Models
  children:
  - Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.#ctor
  - Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.#ctor(System.String)
  - Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.Format
  langs:
  - csharp
  - vb
  name: ActivateApplicationPackageParameters
  fullName: Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ActivateApplicationPackageParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ActivateApplicationPackageParameters
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ActivateApplicationPackageParameters.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nParameters for an ApplicationOperations.ActivateApplicationPackage\r\nrequest.\r\n"
  example: []
  syntax:
    content: public class ActivateApplicationPackageParameters
    content.vb: Public Class ActivateApplicationPackageParameters
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.Format
  commentId: P:Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.Format
  id: Format
  parent: Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters
  langs:
  - csharp
  - vb
  name: Format
  fullName: Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.Format
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ActivateApplicationPackageParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Format
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ActivateApplicationPackageParameters.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nRequired. Gets or sets the format of the application package binary\r\nfile.\r\n"
  example: []
  syntax:
    content: >-
      public string Format

      {

          get;

          set;

      }
    content.vb: Public Property Format As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.#ctor
  commentId: M:Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters
  langs:
  - csharp
  - vb
  name: ActivateApplicationPackageParameters()
  fullName: Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.ActivateApplicationPackageParameters()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ActivateApplicationPackageParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ActivateApplicationPackageParameters.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nInitializes a new instance of the\r\nActivateApplicationPackageParameters class.\r\n"
  example: []
  syntax:
    content: public ActivateApplicationPackageParameters()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.#ctor(System.String)
  commentId: M:Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters
  langs:
  - csharp
  - vb
  name: ActivateApplicationPackageParameters(String)
  fullName: Microsoft.Azure.Management.Batch.Models.ActivateApplicationPackageParameters.ActivateApplicationPackageParameters(System.String)
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ActivateApplicationPackageParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Batch/BatchManagement/Generated/Models/ActivateApplicationPackageParameters.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.Batch
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\r\nInitializes a new instance of the\r\nActivateApplicationPackageParameters class with required arguments.\r\n"
  example: []
  syntax:
    content: public ActivateApplicationPackageParameters(string format)
    content.vb: Public Sub New(format As String)
    parameters:
    - id: format
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Batch.Models
  isExternal: false
  name: Microsoft.Azure.Management.Batch.Models
  fullName: Microsoft.Azure.Management.Batch.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
