items:
- uid: Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation
  commentId: T:Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation
  id: ITenantConfigurationSyncStateOperation
  parent: Microsoft.Azure.Management.ApiManagement
  children:
  - Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation.GetAsync(System.String,System.String,System.Threading.CancellationToken)
  langs:
  - csharp
  - vb
  name: ITenantConfigurationSyncStateOperation
  fullName: Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation
  type: Interface
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/ITenantConfigurationSyncStateOperation.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ITenantConfigurationSyncStateOperation
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/ITenantConfigurationSyncStateOperation.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement
  summary: "\r\nOperation to return the status of the most recent synchronization\r\nbetween configuration database and the Git repository.\r\n"
  example: []
  syntax:
    content: public interface ITenantConfigurationSyncStateOperation
    content.vb: Public Interface ITenantConfigurationSyncStateOperation
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation.GetAsync(System.String,System.String,System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation.GetAsync(System.String,System.String,System.Threading.CancellationToken)
  id: GetAsync(System.String,System.String,System.Threading.CancellationToken)
  parent: Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation
  langs:
  - csharp
  - vb
  name: GetAsync(String, String, CancellationToken)
  fullName: Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation.GetAsync(System.String, System.String, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/ITenantConfigurationSyncStateOperation.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: GetAsync
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/ITenantConfigurationSyncStateOperation.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement
  summary: "\r\nGets Tenant Configuration Synchronization State operation result.\r\n"
  example: []
  syntax:
    content: Task<TenantConfigurationSyncStateResponse> GetAsync(string resourceGroupName, string serviceName, CancellationToken cancellationToken)
    content.vb: Function GetAsync(resourceGroupName As String, serviceName As String, cancellationToken As CancellationToken) As Task(Of TenantConfigurationSyncStateResponse)
    parameters:
    - id: resourceGroupName
      type: System.String
      description: "\r\nThe name of the resource group.\r\n"
    - id: serviceName
      type: System.String
      description: "\r\nThe name of the Api Management service.\r\n"
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: "\r\nCancellation token.\r\n"
    return:
      type: System.Threading.Tasks.Task{Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse}
      description: "\r\nGet Tenant Configuration Synchronization State response details.\r\n"
references:
- uid: Microsoft.Azure.Management.ApiManagement
  isExternal: false
  name: Microsoft.Azure.Management.ApiManagement
  fullName: Microsoft.Azure.Management.ApiManagement
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  name: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Threading.Tasks.Task{Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<TenantConfigurationSyncStateResponse>
  fullName: System.Threading.Tasks.Task<Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse>
  fullname.vb: System.Threading.Tasks.Task(Of Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse)
  name.vb: Task(Of TenantConfigurationSyncStateResponse)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
    name: TenantConfigurationSyncStateResponse
    fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
    name: TenantConfigurationSyncStateResponse
    fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Threading
  isExternal: false
  name: System.Threading
  fullName: System.Threading
- uid: System.Threading.Tasks.Task`1
  parent: System.Threading.Tasks
  isExternal: true
  name: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  fullname.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - name: TResult
    fullName: TResult
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: TResult
    fullName: TResult
  - name: )
    fullName: )
- uid: System.Threading.Tasks
  isExternal: false
  name: System.Threading.Tasks
  fullName: System.Threading.Tasks
