items:
- uid: Microsoft.Azure.Management.ApiManagement.IUserApplicationsOperations
  commentId: T:Microsoft.Azure.Management.ApiManagement.IUserApplicationsOperations
  id: IUserApplicationsOperations
  parent: Microsoft.Azure.Management.ApiManagement
  children: []
  langs:
  - csharp
  - vb
  name: IUserApplicationsOperations
  fullName: Microsoft.Azure.Management.ApiManagement.IUserApplicationsOperations
  type: Interface
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/IUserApplicationsOperations.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: IUserApplicationsOperations
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/IUserApplicationsOperations.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement
  summary: "\r\nOperations for managing User Applications.\r\n"
  example: []
  syntax:
    content: public interface IUserApplicationsOperations
    content.vb: Public Interface IUserApplicationsOperations
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Microsoft.Azure.Management.ApiManagement
  isExternal: false
  name: Microsoft.Azure.Management.ApiManagement
  fullName: Microsoft.Azure.Management.ApiManagement
