items:
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse
  commentId: T:Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse
  id: TenantConfigurationLongRunningOperationResponse
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels
  children:
  - Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse.#ctor
  - Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse.OperationResult
  langs:
  - csharp
  - vb
  name: TenantConfigurationLongRunningOperationResponse
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationLongRunningOperationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: TenantConfigurationLongRunningOperationResponse
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationLongRunningOperationResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement.SmapiModels
  summary: "\r\nA standard service response for long running tenant configuration\r\noperations.\r\n"
  example: []
  syntax:
    content: 'public class TenantConfigurationLongRunningOperationResponse : TenantLongRunningOperationResponse'
    content.vb: >-
      Public Class TenantConfigurationLongRunningOperationResponse

          Inherits TenantLongRunningOperationResponse
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse
  inheritedMembers:
  - Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse.OperationStatusLink
  - Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse.RetryAfter
  - Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse.Status
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse.OperationResult
  commentId: P:Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse.OperationResult
  id: OperationResult
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse
  langs:
  - csharp
  - vb
  name: OperationResult
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse.OperationResult
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationLongRunningOperationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: OperationResult
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationLongRunningOperationResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement.SmapiModels
  summary: "\r\nOptional. Gets or sets error description of the opertion. Equals to\r\nnull is no errors.\r\n"
  example: []
  syntax:
    content: >-
      public OperationResultContract OperationResult

      {

          get;

          set;

      }
    content.vb: Public Property OperationResult As OperationResultContract
    parameters: []
    return:
      type: Microsoft.Azure.Management.ApiManagement.SmapiModels.OperationResultContract
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse.#ctor
  commentId: M:Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse
  langs:
  - csharp
  - vb
  name: TenantConfigurationLongRunningOperationResponse()
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationLongRunningOperationResponse.TenantConfigurationLongRunningOperationResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationLongRunningOperationResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationLongRunningOperationResponse.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement.SmapiModels
  summary: "\r\nInitializes a new instance of the\r\nTenantConfigurationLongRunningOperationResponse class.\r\n"
  example: []
  syntax:
    content: public TenantConfigurationLongRunningOperationResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels
  isExternal: false
  name: Microsoft.Azure.Management.ApiManagement.SmapiModels
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels
  isExternal: false
  name: TenantLongRunningOperationResponse
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse.OperationStatusLink
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse
  isExternal: false
  name: OperationStatusLink
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse.OperationStatusLink
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse.RetryAfter
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse
  isExternal: false
  name: RetryAfter
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse.RetryAfter
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse.Status
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse
  isExternal: false
  name: Status
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantLongRunningOperationResponse.Status
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.OperationResultContract
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels
  isExternal: false
  name: OperationResultContract
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.OperationResultContract
