items:
- uid: Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions
  commentId: T:Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions
  id: TenantConfigurationSyncStateOperationExtensions
  parent: Microsoft.Azure.Management.ApiManagement
  children:
  - Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions.Get(Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation,System.String,System.String)
  - Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions.GetAsync(Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation,System.String,System.String)
  langs:
  - csharp
  - vb
  name: TenantConfigurationSyncStateOperationExtensions
  fullName: Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/TenantConfigurationSyncStateOperationExtensions.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: TenantConfigurationSyncStateOperationExtensions
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/TenantConfigurationSyncStateOperationExtensions.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement
  summary: "\r\n.Net client wrapper for the REST API for Azure ApiManagement Service\r\n"
  example: []
  syntax:
    content: public class TenantConfigurationSyncStateOperationExtensions
    content.vb: Public Class TenantConfigurationSyncStateOperationExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions.Get(Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions.Get(Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation,System.String,System.String)
  id: Get(Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation,System.String,System.String)
  parent: Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions
  langs:
  - csharp
  - vb
  name: Get(ITenantConfigurationSyncStateOperation, String, String)
  fullName: Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions.Get(Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation, System.String, System.String)
  type: Method
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/TenantConfigurationSyncStateOperationExtensions.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Get
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/TenantConfigurationSyncStateOperationExtensions.cs
    startLine: 51
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement
  summary: "\r\nGets Tenant Configuration Synchronization State operation result.\r\n"
  example: []
  syntax:
    content: public static TenantConfigurationSyncStateResponse Get(ITenantConfigurationSyncStateOperation operations, string resourceGroupName, string serviceName)
    content.vb: Public Shared Function Get(operations As ITenantConfigurationSyncStateOperation, resourceGroupName As String, serviceName As String) As TenantConfigurationSyncStateResponse
    parameters:
    - id: operations
      type: Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation
      description: "\r\nReference to the\r\nMicrosoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation.\r\n"
    - id: resourceGroupName
      type: System.String
      description: "\r\nRequired. The name of the resource group.\r\n"
    - id: serviceName
      type: System.String
      description: "\r\nRequired. The name of the Api Management service.\r\n"
    return:
      type: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
      description: "\r\nGet Tenant Configuration Synchronization State response details.\r\n"
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions.GetAsync(Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions.GetAsync(Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation,System.String,System.String)
  id: GetAsync(Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation,System.String,System.String)
  parent: Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions
  langs:
  - csharp
  - vb
  name: GetAsync(ITenantConfigurationSyncStateOperation, String, String)
  fullName: Microsoft.Azure.Management.ApiManagement.TenantConfigurationSyncStateOperationExtensions.GetAsync(Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation, System.String, System.String)
  type: Method
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/TenantConfigurationSyncStateOperationExtensions.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: GetAsync
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/TenantConfigurationSyncStateOperationExtensions.cs
    startLine: 76
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement
  summary: "\r\nGets Tenant Configuration Synchronization State operation result.\r\n"
  example: []
  syntax:
    content: public static Task<TenantConfigurationSyncStateResponse> GetAsync(ITenantConfigurationSyncStateOperation operations, string resourceGroupName, string serviceName)
    content.vb: Public Shared Function GetAsync(operations As ITenantConfigurationSyncStateOperation, resourceGroupName As String, serviceName As String) As Task(Of TenantConfigurationSyncStateResponse)
    parameters:
    - id: operations
      type: Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation
      description: "\r\nReference to the\r\nMicrosoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation.\r\n"
    - id: resourceGroupName
      type: System.String
      description: "\r\nRequired. The name of the resource group.\r\n"
    - id: serviceName
      type: System.String
      description: "\r\nRequired. The name of the Api Management service.\r\n"
    return:
      type: System.Threading.Tasks.Task{Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse}
      description: "\r\nGet Tenant Configuration Synchronization State response details.\r\n"
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Microsoft.Azure.Management.ApiManagement
  isExternal: false
  name: Microsoft.Azure.Management.ApiManagement
  fullName: Microsoft.Azure.Management.ApiManagement
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation
  parent: Microsoft.Azure.Management.ApiManagement
  isExternal: false
  name: ITenantConfigurationSyncStateOperation
  fullName: Microsoft.Azure.Management.ApiManagement.ITenantConfigurationSyncStateOperation
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels
  isExternal: false
  name: TenantConfigurationSyncStateResponse
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels
  isExternal: false
  name: Microsoft.Azure.Management.ApiManagement.SmapiModels
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels
- uid: System.Threading.Tasks.Task{Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<TenantConfigurationSyncStateResponse>
  fullName: System.Threading.Tasks.Task<Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse>
  fullname.vb: System.Threading.Tasks.Task(Of Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse)
  name.vb: Task(Of TenantConfigurationSyncStateResponse)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
    name: TenantConfigurationSyncStateResponse
    fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
    name: TenantConfigurationSyncStateResponse
    fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
  - name: )
    fullName: )
- uid: System.Threading.Tasks.Task`1
  parent: System.Threading.Tasks
  isExternal: true
  name: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  fullname.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - name: TResult
    fullName: TResult
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: TResult
    fullName: TResult
  - name: )
    fullName: )
- uid: System.Threading.Tasks
  isExternal: false
  name: System.Threading.Tasks
  fullName: System.Threading.Tasks
