items:
- uid: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration
  commentId: T:Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration
  id: VirtualNetworkConfiguration
  parent: Microsoft.Azure.Management.ApiManagement.Models
  children:
  - Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.#ctor
  - Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.Location
  - Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.SubnetName
  - Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.VnetId
  langs:
  - csharp
  - vb
  name: VirtualNetworkConfiguration
  fullName: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/Models/VirtualNetworkConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: VirtualNetworkConfiguration
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/Models/VirtualNetworkConfiguration.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement.Models
  summary: "\r\nConfiguration of a virtual network.\r\n"
  example: []
  syntax:
    content: public class VirtualNetworkConfiguration
    content.vb: Public Class VirtualNetworkConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.Location
  commentId: P:Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.Location
  id: Location
  parent: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration
  langs:
  - csharp
  - vb
  name: Location
  fullName: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.Location
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/Models/VirtualNetworkConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Location
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/Models/VirtualNetworkConfiguration.cs
    startLine: 36
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement.Models
  summary: "\r\nOptional. Gets or sets virtual network location name.\r\n"
  example: []
  syntax:
    content: >-
      public string Location

      {

          get;

          set;

      }
    content.vb: Public Property Location As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.SubnetName
  commentId: P:Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.SubnetName
  id: SubnetName
  parent: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration
  langs:
  - csharp
  - vb
  name: SubnetName
  fullName: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.SubnetName
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/Models/VirtualNetworkConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: SubnetName
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/Models/VirtualNetworkConfiguration.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement.Models
  summary: "\r\nOptional. Gets or sets subnetwork name.\r\n"
  example: []
  syntax:
    content: >-
      public string SubnetName

      {

          get;

          set;

      }
    content.vb: Public Property SubnetName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.VnetId
  commentId: P:Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.VnetId
  id: VnetId
  parent: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration
  langs:
  - csharp
  - vb
  name: VnetId
  fullName: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.VnetId
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/Models/VirtualNetworkConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: VnetId
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/Models/VirtualNetworkConfiguration.cs
    startLine: 58
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement.Models
  summary: "\r\nOptional. Gets or sets virtual network id.\r\n"
  example: []
  syntax:
    content: >-
      public Guid VnetId

      {

          get;

          set;

      }
    content.vb: Public Property VnetId As Guid
    parameters: []
    return:
      type: System.Guid
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration
  langs:
  - csharp
  - vb
  name: VirtualNetworkConfiguration()
  fullName: Microsoft.Azure.Management.ApiManagement.Models.VirtualNetworkConfiguration.VirtualNetworkConfiguration()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/Models/VirtualNetworkConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/Models/VirtualNetworkConfiguration.cs
    startLine: 67
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement.Models
  summary: "\r\nInitializes a new instance of the VirtualNetworkConfiguration class.\r\n"
  example: []
  syntax:
    content: public VirtualNetworkConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.ApiManagement.Models
  isExternal: false
  name: Microsoft.Azure.Management.ApiManagement.Models
  fullName: Microsoft.Azure.Management.ApiManagement.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  fullName: System.Guid
