items:
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
  commentId: T:Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
  id: TenantConfigurationSyncStateResponse
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels
  children:
  - Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse.#ctor
  - Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse.Value
  langs:
  - csharp
  - vb
  name: TenantConfigurationSyncStateResponse
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationSyncStateResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: TenantConfigurationSyncStateResponse
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationSyncStateResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement.SmapiModels
  summary: "\r\nGet Tenant Configuration Synchronization State response details.\r\n"
  example: []
  syntax:
    content: 'public class TenantConfigurationSyncStateResponse : AzureOperationResponse'
    content.vb: >-
      Public Class TenantConfigurationSyncStateResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse.Value
  commentId: P:Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse.Value
  id: Value
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
  langs:
  - csharp
  - vb
  name: Value
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse.Value
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationSyncStateResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Value
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationSyncStateResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement.SmapiModels
  summary: "\r\nOptional. Gets or sets result of the Get Tenant Configuration\r\nSynchronization state operation.\r\n"
  example: []
  syntax:
    content: >-
      public TenantConfigurationSyncStateContract Value

      {

          get;

          set;

      }
    content.vb: Public Property Value As TenantConfigurationSyncStateContract
    parameters: []
    return:
      type: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateContract
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse.#ctor
  commentId: M:Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse
  langs:
  - csharp
  - vb
  name: TenantConfigurationSyncStateResponse()
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateResponse.TenantConfigurationSyncStateResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationSyncStateResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/SmapiModels/TenantConfigurationSyncStateResponse.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.ApiManagement
  namespace: Microsoft.Azure.Management.ApiManagement.SmapiModels
  summary: "\r\nInitializes a new instance of the\r\nTenantConfigurationSyncStateResponse class.\r\n"
  example: []
  syntax:
    content: public TenantConfigurationSyncStateResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels
  isExternal: false
  name: Microsoft.Azure.Management.ApiManagement.SmapiModels
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateContract
  parent: Microsoft.Azure.Management.ApiManagement.SmapiModels
  isExternal: false
  name: TenantConfigurationSyncStateContract
  fullName: Microsoft.Azure.Management.ApiManagement.SmapiModels.TenantConfigurationSyncStateContract
