items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse
  id: ApplicationGatewayListResponse
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.ApplicationGateways
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.NextLink
  langs:
  - csharp
  - vb
  name: ApplicationGatewayListResponse
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ApplicationGatewayListResponse
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayListResponse.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nResponse for ListLoadBalancers Api service call\r\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayListResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ApplicationGatewayListResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.ApplicationGateways
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.ApplicationGateways
  id: ApplicationGateways
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse
  langs:
  - csharp
  - vb
  name: ApplicationGateways
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.ApplicationGateways
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ApplicationGateways
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayListResponse.cs
    startLine: 40
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets a list of ApplicationGateways in a resource group\r\n"
  example: []
  syntax:
    content: >-
      public IList<ApplicationGateway> ApplicationGateways

      {

          get;

          set;

      }
    content.vb: Public Property ApplicationGateways As IList(Of ApplicationGateway)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGateway}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.NextLink
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.NextLink
  id: NextLink
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse
  langs:
  - csharp
  - vb
  name: NextLink
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.NextLink
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: NextLink
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayListResponse.cs
    startLine: 51
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets the URL to get the next set of results.\r\n"
  example: []
  syntax:
    content: >-
      public string NextLink

      {

          get;

          set;

      }
    content.vb: Public Property NextLink As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse
  langs:
  - csharp
  - vb
  name: ApplicationGatewayListResponse()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayListResponse.ApplicationGatewayListResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayListResponse.cs
    startLine: 61
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nInitializes a new instance of the ApplicationGatewayListResponse\r\nclass.\r\n"
  example: []
  syntax:
    content: public ApplicationGatewayListResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGateway}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<ApplicationGateway>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.Network.Models.ApplicationGateway>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.Network.Models.ApplicationGateway)
  name.vb: IList(Of ApplicationGateway)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Network.Models.ApplicationGateway
    name: ApplicationGateway
    fullName: Microsoft.Azure.Management.Network.Models.ApplicationGateway
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Network.Models.ApplicationGateway
    name: ApplicationGateway
    fullName: Microsoft.Azure.Management.Network.Models.ApplicationGateway
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
