items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse
  id: ApplicationGatewayGetResponse
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse.ApplicationGateway
  langs:
  - csharp
  - vb
  name: ApplicationGatewayGetResponse
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ApplicationGatewayGetResponse
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nResponse of a GET ApplicationGateway operation\r\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayGetResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ApplicationGatewayGetResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse.ApplicationGateway
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse.ApplicationGateway
  id: ApplicationGateway
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: ApplicationGateway
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse.ApplicationGateway
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ApplicationGateway
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets a ApplicationGateway in a resource group\r\n"
  example: []
  syntax:
    content: >-
      public ApplicationGateway ApplicationGateway

      {

          get;

          set;

      }
    content.vb: Public Property ApplicationGateway As ApplicationGateway
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.ApplicationGateway
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: ApplicationGatewayGetResponse()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayGetResponse.ApplicationGatewayGetResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nInitializes a new instance of the ApplicationGatewayGetResponse\r\nclass.\r\n"
  example: []
  syntax:
    content: public ApplicationGatewayGetResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGateway
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: ApplicationGateway
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGateway
