items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule
  id: ApplicationGatewayRequestRoutingRule
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.BackendAddressPool
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.BackendHttpSettings
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.HttpListener
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.ProvisioningState
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.RuleType
  langs:
  - csharp
  - vb
  name: ApplicationGatewayRequestRoutingRule
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ApplicationGatewayRequestRoutingRule
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nRequest routing rule of application gateway\r\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayRequestRoutingRule : ChildResource'
    content.vb: >-
      Public Class ApplicationGatewayRequestRoutingRule

          Inherits ChildResource
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Network.Models.ResourceId
  - Microsoft.Azure.Management.Network.Models.ChildResource
  inheritedMembers:
  - Microsoft.Azure.Management.Network.Models.ChildResource.Etag
  - Microsoft.Azure.Management.Network.Models.ChildResource.Name
  - Microsoft.Azure.Management.Network.Models.ResourceId.Id
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.BackendAddressPool
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.BackendAddressPool
  id: BackendAddressPool
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule
  langs:
  - csharp
  - vb
  name: BackendAddressPool
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.BackendAddressPool
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: BackendAddressPool
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets or sets backend address pool resource of application\r\ngateway\r\n"
  example: []
  syntax:
    content: >-
      public ResourceId BackendAddressPool

      {

          get;

          set;

      }
    content.vb: Public Property BackendAddressPool As ResourceId
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.ResourceId
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.BackendHttpSettings
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.BackendHttpSettings
  id: BackendHttpSettings
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule
  langs:
  - csharp
  - vb
  name: BackendHttpSettings
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.BackendHttpSettings
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: BackendHttpSettings
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets or sets frontend port resource of application\r\ngateway\r\n"
  example: []
  syntax:
    content: >-
      public ResourceId BackendHttpSettings

      {

          get;

          set;

      }
    content.vb: Public Property BackendHttpSettings As ResourceId
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.ResourceId
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.HttpListener
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.HttpListener
  id: HttpListener
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule
  langs:
  - csharp
  - vb
  name: HttpListener
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.HttpListener
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: HttpListener
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
    startLine: 62
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets or sets http listener resource of application\r\ngateway\r\n"
  example: []
  syntax:
    content: >-
      public ResourceId HttpListener

      {

          get;

          set;

      }
    content.vb: Public Property HttpListener As ResourceId
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.ResourceId
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.ProvisioningState
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ProvisioningState
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
    startLine: 74
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets or sets Provisioning state of the request routing\r\nrule resource Updating/Deleting/Failed\r\n"
  example: []
  syntax:
    content: >-
      public string ProvisioningState

      {

          get;

          set;

      }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.RuleType
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.RuleType
  id: RuleType
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule
  langs:
  - csharp
  - vb
  name: RuleType
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.RuleType
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: RuleType
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
    startLine: 85
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets or sets the rule type\r\n"
  example: []
  syntax:
    content: >-
      public string RuleType

      {

          get;

          set;

      }
    content.vb: Public Property RuleType As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule
  langs:
  - csharp
  - vb
  name: ApplicationGatewayRequestRoutingRule()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayRequestRoutingRule.ApplicationGatewayRequestRoutingRule()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayRequestRoutingRule.cs
    startLine: 95
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nInitializes a new instance of the\r\nApplicationGatewayRequestRoutingRule class.\r\n"
  example: []
  syntax:
    content: public ApplicationGatewayRequestRoutingRule()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Network.Models.ResourceId
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: ResourceId
  fullName: Microsoft.Azure.Management.Network.Models.ResourceId
- uid: Microsoft.Azure.Management.Network.Models.ChildResource
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: ChildResource
  fullName: Microsoft.Azure.Management.Network.Models.ChildResource
- uid: Microsoft.Azure.Management.Network.Models.ChildResource.Etag
  parent: Microsoft.Azure.Management.Network.Models.ChildResource
  isExternal: false
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.ChildResource.Etag
- uid: Microsoft.Azure.Management.Network.Models.ChildResource.Name
  parent: Microsoft.Azure.Management.Network.Models.ChildResource
  isExternal: false
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.ChildResource.Name
- uid: Microsoft.Azure.Management.Network.Models.ResourceId.Id
  parent: Microsoft.Azure.Management.Network.Models.ResourceId
  isExternal: false
  name: Id
  fullName: Microsoft.Azure.Management.Network.Models.ResourceId.Id
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
