items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration
  id: ApplicationGatewayFrontendIPConfiguration
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PrivateIPAddress
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PrivateIPAllocationMethod
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.ProvisioningState
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PublicIPAddress
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.Subnet
  langs:
  - csharp
  - vb
  name: ApplicationGatewayFrontendIPConfiguration
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ApplicationGatewayFrontendIPConfiguration
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nFrontend IP configuration of application gateway\r\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayFrontendIPConfiguration : ChildResource'
    content.vb: >-
      Public Class ApplicationGatewayFrontendIPConfiguration

          Inherits ChildResource
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Network.Models.ResourceId
  - Microsoft.Azure.Management.Network.Models.ChildResource
  inheritedMembers:
  - Microsoft.Azure.Management.Network.Models.ChildResource.Etag
  - Microsoft.Azure.Management.Network.Models.ChildResource.Name
  - Microsoft.Azure.Management.Network.Models.ResourceId.Id
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PrivateIPAddress
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PrivateIPAddress
  id: PrivateIPAddress
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration
  langs:
  - csharp
  - vb
  name: PrivateIPAddress
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PrivateIPAddress
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: PrivateIPAddress
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets or sets the privateIPAddress of the Network\r\nInterface IP Configuration\r\n"
  example: []
  syntax:
    content: >-
      public string PrivateIPAddress

      {

          get;

          set;

      }
    content.vb: Public Property PrivateIPAddress As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PrivateIPAllocationMethod
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PrivateIPAllocationMethod
  id: PrivateIPAllocationMethod
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration
  langs:
  - csharp
  - vb
  name: PrivateIPAllocationMethod
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PrivateIPAllocationMethod
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: PrivateIPAllocationMethod
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets or sets PrivateIP allocation method (Static/Dynamic)\r\n"
  example: []
  syntax:
    content: >-
      public string PrivateIPAllocationMethod

      {

          get;

          set;

      }
    content.vb: Public Property PrivateIPAllocationMethod As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.ProvisioningState
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ProvisioningState
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
    startLine: 61
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets or sets Provisioning state of the PublicIP resource\r\nUpdating/Deleting/Failed\r\n"
  example: []
  syntax:
    content: >-
      public string ProvisioningState

      {

          get;

          set;

      }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PublicIPAddress
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PublicIPAddress
  id: PublicIPAddress
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration
  langs:
  - csharp
  - vb
  name: PublicIPAddress
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.PublicIPAddress
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: PublicIPAddress
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
    startLine: 72
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets or sets the reference of the PublicIP resource\r\n"
  example: []
  syntax:
    content: >-
      public ResourceId PublicIPAddress

      {

          get;

          set;

      }
    content.vb: Public Property PublicIPAddress As ResourceId
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.ResourceId
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.Subnet
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.Subnet
  id: Subnet
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration
  langs:
  - csharp
  - vb
  name: Subnet
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.Subnet
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Subnet
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
    startLine: 83
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets or sets the reference of the subnet resource\r\n"
  example: []
  syntax:
    content: >-
      public ResourceId Subnet

      {

          get;

          set;

      }
    content.vb: Public Property Subnet As ResourceId
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.ResourceId
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration
  langs:
  - csharp
  - vb
  name: ApplicationGatewayFrontendIPConfiguration()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfiguration.ApplicationGatewayFrontendIPConfiguration()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayFrontendIPConfiguration.cs
    startLine: 93
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nInitializes a new instance of the\r\nApplicationGatewayFrontendIPConfiguration class.\r\n"
  example: []
  syntax:
    content: public ApplicationGatewayFrontendIPConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Network.Models.ResourceId
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: ResourceId
  fullName: Microsoft.Azure.Management.Network.Models.ResourceId
- uid: Microsoft.Azure.Management.Network.Models.ChildResource
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: ChildResource
  fullName: Microsoft.Azure.Management.Network.Models.ChildResource
- uid: Microsoft.Azure.Management.Network.Models.ChildResource.Etag
  parent: Microsoft.Azure.Management.Network.Models.ChildResource
  isExternal: false
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.ChildResource.Etag
- uid: Microsoft.Azure.Management.Network.Models.ChildResource.Name
  parent: Microsoft.Azure.Management.Network.Models.ChildResource
  isExternal: false
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.ChildResource.Name
- uid: Microsoft.Azure.Management.Network.Models.ResourceId.Id
  parent: Microsoft.Azure.Management.Network.Models.ResourceId
  isExternal: false
  name: Id
  fullName: Microsoft.Azure.Management.Network.Models.ResourceId.Id
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
