items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse
  id: ApplicationGatewayPutResponse
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse.ApplicationGateway
  langs:
  - csharp
  - vb
  name: ApplicationGatewayPutResponse
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayPutResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ApplicationGatewayPutResponse
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayPutResponse.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nResponse of Put ApplicationGateway operation\r\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayPutResponse : UpdateOperationResponse'
    content.vb: >-
      Public Class ApplicationGatewayPutResponse

          Inherits UpdateOperationResponse
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Network.Models.ResourceProviderErrorResponse
  - Microsoft.Azure.Management.Network.Models.RetriableOperationResponse
  - Microsoft.Azure.Management.Network.Models.UpdateOperationResponse
  inheritedMembers:
  - Microsoft.Azure.Management.Network.Models.UpdateOperationResponse.AzureAsyncOperation
  - Microsoft.Azure.Management.Network.Models.RetriableOperationResponse.RetryAfter
  - Microsoft.Azure.Management.Network.Models.ResourceProviderErrorResponse.Error
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse.ApplicationGateway
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse.ApplicationGateway
  id: ApplicationGateway
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse
  langs:
  - csharp
  - vb
  name: ApplicationGateway
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse.ApplicationGateway
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayPutResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ApplicationGateway
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayPutResponse.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nOptional. Gets Application Gateway that exists in a resource group\r\n"
  example: []
  syntax:
    content: >-
      public ApplicationGateway ApplicationGateway

      {

          get;

          set;

      }
    content.vb: Public Property ApplicationGateway As ApplicationGateway
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.ApplicationGateway
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse
  langs:
  - csharp
  - vb
  name: ApplicationGatewayPutResponse()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPutResponse.ApplicationGatewayPutResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayPutResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayPutResponse.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.Network
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\r\nInitializes a new instance of the ApplicationGatewayPutResponse\r\nclass.\r\n"
  example: []
  syntax:
    content: public ApplicationGatewayPutResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Network.Models.ResourceProviderErrorResponse
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: ResourceProviderErrorResponse
  fullName: Microsoft.Azure.Management.Network.Models.ResourceProviderErrorResponse
- uid: Microsoft.Azure.Management.Network.Models.RetriableOperationResponse
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: RetriableOperationResponse
  fullName: Microsoft.Azure.Management.Network.Models.RetriableOperationResponse
- uid: Microsoft.Azure.Management.Network.Models.UpdateOperationResponse
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: UpdateOperationResponse
  fullName: Microsoft.Azure.Management.Network.Models.UpdateOperationResponse
- uid: Microsoft.Azure.Management.Network.Models.UpdateOperationResponse.AzureAsyncOperation
  parent: Microsoft.Azure.Management.Network.Models.UpdateOperationResponse
  isExternal: false
  name: AzureAsyncOperation
  fullName: Microsoft.Azure.Management.Network.Models.UpdateOperationResponse.AzureAsyncOperation
- uid: Microsoft.Azure.Management.Network.Models.RetriableOperationResponse.RetryAfter
  parent: Microsoft.Azure.Management.Network.Models.RetriableOperationResponse
  isExternal: false
  name: RetryAfter
  fullName: Microsoft.Azure.Management.Network.Models.RetriableOperationResponse.RetryAfter
- uid: Microsoft.Azure.Management.Network.Models.ResourceProviderErrorResponse.Error
  parent: Microsoft.Azure.Management.Network.Models.ResourceProviderErrorResponse
  isExternal: false
  name: Error
  fullName: Microsoft.Azure.Management.Network.Models.ResourceProviderErrorResponse.Error
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGateway
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: ApplicationGateway
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGateway
