items:
- uid: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse
  commentId: T:Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse
  id: GetResourceStorageConfigResponse
  parent: Microsoft.Azure.Management.RecoveryServices.Models
  children:
  - Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.#ctor
  - Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Id
  - Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Name
  - Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Properties
  - Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Type
  langs:
  - csharp
  - vb
  name: GetResourceStorageConfigResponse
  fullName: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: GetResourceStorageConfigResponse
    path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices
  namespace: Microsoft.Azure.Management.RecoveryServices.Models
  summary: "\r\nThe definition of a get resource storage config response.\r\n"
  example: []
  syntax:
    content: 'public class GetResourceStorageConfigResponse : AzureOperationResponse'
    content.vb: >-
      Public Class GetResourceStorageConfigResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Id
  commentId: P:Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Id
  id: Id
  parent: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse
  langs:
  - csharp
  - vb
  name: Id
  fullName: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Id
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Id
    path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices
  namespace: Microsoft.Azure.Management.RecoveryServices.Models
  summary: "\r\nOptional. Gets or sets the resource ID.\r\n"
  example: []
  syntax:
    content: >-
      public string Id

      {

          get;

          set;

      }
    content.vb: Public Property Id As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Name
  commentId: P:Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Name
  id: Name
  parent: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Name
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Name
    path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices
  namespace: Microsoft.Azure.Management.RecoveryServices.Models
  summary: "\r\nOptional. Gets or sets the resource Name.\r\n"
  example: []
  syntax:
    content: >-
      public string Name

      {

          get;

          set;

      }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Properties
  commentId: P:Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Properties
  id: Properties
  parent: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse
  langs:
  - csharp
  - vb
  name: Properties
  fullName: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Properties
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Properties
    path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
    startLine: 60
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices
  namespace: Microsoft.Azure.Management.RecoveryServices.Models
  summary: "\r\nOptional. The resource storage details.\r\n"
  example: []
  syntax:
    content: >-
      public StorageDetails Properties

      {

          get;

          set;

      }
    content.vb: Public Property Properties As StorageDetails
    parameters: []
    return:
      type: Microsoft.Azure.Management.RecoveryServices.Models.StorageDetails
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Type
  commentId: P:Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Type
  id: Type
  parent: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse
  langs:
  - csharp
  - vb
  name: Type
  fullName: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.Type
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Type
    path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
    startLine: 71
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices
  namespace: Microsoft.Azure.Management.RecoveryServices.Models
  summary: "\r\nOptional. Gets or sets the resource Type.\r\n"
  example: []
  syntax:
    content: >-
      public string Type

      {

          get;

          set;

      }
    content.vb: Public Property Type As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.#ctor
  commentId: M:Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse
  langs:
  - csharp
  - vb
  name: GetResourceStorageConfigResponse()
  fullName: Microsoft.Azure.Management.RecoveryServices.Models.GetResourceStorageConfigResponse.GetResourceStorageConfigResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/RecoveryServices/RecoveryServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
    startLine: 81
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices
  namespace: Microsoft.Azure.Management.RecoveryServices.Models
  summary: "\r\nInitializes a new instance of the GetResourceStorageConfigResponse\r\nclass.\r\n"
  example: []
  syntax:
    content: public GetResourceStorageConfigResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.RecoveryServices.Models
  isExternal: false
  name: Microsoft.Azure.Management.RecoveryServices.Models
  fullName: Microsoft.Azure.Management.RecoveryServices.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.RecoveryServices.Models.StorageDetails
  parent: Microsoft.Azure.Management.RecoveryServices.Models
  isExternal: false
  name: StorageDetails
  fullName: Microsoft.Azure.Management.RecoveryServices.Models.StorageDetails
