items:
- uid: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult
  commentId: T:Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult
  id: SlotConfigNamesResult
  parent: Microsoft.Azure.Management.WebSites.Models
  children:
  - Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult.#ctor
  - Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult.Resource
  langs:
  - csharp
  - vb
  name: SlotConfigNamesResult
  fullName: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult
  type: Class
  source:
    remote:
      path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNamesResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: SlotConfigNamesResult
    path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNamesResult.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nList of slot specific settings.\r\n"
  example: []
  syntax:
    content: 'public class SlotConfigNamesResult : AzureOperationResponse'
    content.vb: >-
      Public Class SlotConfigNamesResult

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult.Resource
  commentId: P:Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult.Resource
  id: Resource
  parent: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult
  langs:
  - csharp
  - vb
  name: Resource
  fullName: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult.Resource
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNamesResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Resource
    path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNamesResult.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nOptional. Application settings configuration for a site.\r\n"
  example: []
  syntax:
    content: >-
      public SlotConfigNamesEnvelope Resource

      {

          get;

          set;

      }
    content.vb: Public Property Resource As SlotConfigNamesEnvelope
    parameters: []
    return:
      type: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesEnvelope
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult.#ctor
  commentId: M:Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult
  langs:
  - csharp
  - vb
  name: SlotConfigNamesResult()
  fullName: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResult.SlotConfigNamesResult()
  type: Constructor
  source:
    remote:
      path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNamesResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/SlotConfigNamesResult.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nInitializes a new instance of the SlotConfigNamesResult class.\r\n"
  example: []
  syntax:
    content: public SlotConfigNamesResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.Azure.Management.WebSites.Models
  fullName: Microsoft.Azure.Management.WebSites.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesEnvelope
  parent: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: SlotConfigNamesEnvelope
  fullName: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesEnvelope
