items:
- uid: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint
  id: ExtensionEndpointConfiguration.InternalEndpoint
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  children:
  - Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.#ctor
  - Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.#ctor(System.String,System.String,System.Int32)
  - Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Name
  - Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Port
  - Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Protocol
  langs:
  - csharp
  - vb
  name: ExtensionEndpointConfiguration.InternalEndpoint
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint
  type: Class
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: InternalEndpoint
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
    startLine: 242
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nThe extension's internal endpoint configuration.\r\n"
  example: []
  syntax:
    content: public class InternalEndpoint
    content.vb: Public Class InternalEndpoint
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Name
  commentId: P:Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Name
  id: Name
  parent: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Name
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Name
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
    startLine: 250
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nRequired. Required for each internal endpoint. A unique name\r\nfor the external endpoint.\r\n"
  example: []
  syntax:
    content: >-
      public string Name

      {

          get;

          set;

      }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Port
  commentId: P:Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Port
  id: Port
  parent: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint
  langs:
  - csharp
  - vb
  name: Port
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Port
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Port
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
    startLine: 265
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nRequired. Required for each internal endpoint. The port for the\r\nexternal endpoint. You can specify any port number you choose,\r\nbut the port number specified must not collide with port\r\nnumbers occupied by roles in the service. Possible values\r\nrange between 1 and 65535, inclusive\r\n"
  example: []
  syntax:
    content: >-
      public int Port

      {

          get;

          set;

      }
    content.vb: Public Property Port As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Protocol
  commentId: P:Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Protocol
  id: Protocol
  parent: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint
  langs:
  - csharp
  - vb
  name: Protocol
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.Protocol
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Protocol
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
    startLine: 278
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nRequired. Required for each internal endpoint. Transport\r\nprotocol for the endpoint. Its value has to be one of the\r\nfollowing: 'tcp', 'udp', 'http', 'https'.\r\n"
  example: []
  syntax:
    content: >-
      public string Protocol

      {

          get;

          set;

      }
    content.vb: Public Property Protocol As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint
  langs:
  - csharp
  - vb
  name: InternalEndpoint()
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.InternalEndpoint()
  type: Constructor
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
    startLine: 287
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nInitializes a new instance of the InternalEndpoint class.\r\n"
  example: []
  syntax:
    content: public InternalEndpoint()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.#ctor(System.String,System.String,System.Int32)
  commentId: M:Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.#ctor(System.String,System.String,System.Int32)
  id: '#ctor(System.String,System.String,System.Int32)'
  parent: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint
  langs:
  - csharp
  - vb
  name: InternalEndpoint(String, String, Int32)
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.ExtensionEndpointConfiguration.InternalEndpoint.InternalEndpoint(System.String, System.String, System.Int32)
  type: Constructor
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/ExtensionEndpointConfiguration.cs
    startLine: 295
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nInitializes a new instance of the InternalEndpoint class with\r\nrequired arguments.\r\n"
  example: []
  syntax:
    content: public InternalEndpoint(string name, string protocol, int port)
    content.vb: Public Sub New(name As String, protocol As String, port As Integer)
    parameters:
    - id: name
      type: System.String
    - id: protocol
      type: System.String
    - id: port
      type: System.Int32
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Compute.Models
  fullName: Microsoft.WindowsAzure.Management.Compute.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  fullName: System.Int32
