items:
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse
  commentId: T:Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse
  id: SettingsGetResponse
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models
  children:
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.#ctor
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.Value
  langs:
  - csharp
  - vb
  name: SettingsGetResponse
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse
  type: Class
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: SettingsGetResponse
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\r\nThe get setting operation response.\r\n"
  example: []
  syntax:
    content: 'public class SettingsGetResponse : AzureOperationResponse'
    content.vb: >-
      Public Class SettingsGetResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.Value
  commentId: P:Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.Value
  id: Value
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse
  langs:
  - csharp
  - vb
  name: Value
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.Value
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Value
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\r\nOptional. The setting value.\r\n"
  example: []
  syntax:
    content: >-
      public string Value

      {

          get;

          set;

      }
    content.vb: Public Property Value As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.#ctor
  commentId: M:Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse
  langs:
  - csharp
  - vb
  name: SettingsGetResponse()
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.SettingsGetResponse()
  type: Constructor
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
    startLine: 46
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\r\nInitializes a new instance of the SettingsGetResponse class.\r\n"
  example: []
  syntax:
    content: public SettingsGetResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models
  isExternal: false
  name: Microsoft.WindowsAzure.WebSitesExtensions.Models
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
