items:
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits
  commentId: T:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits
  id: WebSiteUpdateConfigurationParameters.SiteLimits
  parent: Microsoft.WindowsAzure.Management.WebSites.Models
  children:
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.#ctor
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxDiskSizeInMb
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxMemoryInMb
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxPercentageCpu
  langs:
  - csharp
  - vb
  name: WebSiteUpdateConfigurationParameters.SiteLimits
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits
  type: Class
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: SiteLimits
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
    startLine: 493
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nPer site limits\r\n"
  example: []
  syntax:
    content: public class SiteLimits
    content.vb: Public Class SiteLimits
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxDiskSizeInMb
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxDiskSizeInMb
  id: MaxDiskSizeInMb
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits
  langs:
  - csharp
  - vb
  name: MaxDiskSizeInMb
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxDiskSizeInMb
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: MaxDiskSizeInMb
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
    startLine: 500
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. Maximum disk size allowed in MB\r\n"
  example: []
  syntax:
    content: >-
      public long ? MaxDiskSizeInMb

      {

          get;

          set;

      }
    content.vb: Public Property MaxDiskSizeInMb As Long?
    parameters: []
    return:
      type: System.Nullable{System.Int64}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxMemoryInMb
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxMemoryInMb
  id: MaxMemoryInMb
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits
  langs:
  - csharp
  - vb
  name: MaxMemoryInMb
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxMemoryInMb
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: MaxMemoryInMb
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
    startLine: 511
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. Maximum memory allowed in MB\r\n"
  example: []
  syntax:
    content: >-
      public long ? MaxMemoryInMb

      {

          get;

          set;

      }
    content.vb: Public Property MaxMemoryInMb As Long?
    parameters: []
    return:
      type: System.Nullable{System.Int64}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxPercentageCpu
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxPercentageCpu
  id: MaxPercentageCpu
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits
  langs:
  - csharp
  - vb
  name: MaxPercentageCpu
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.MaxPercentageCpu
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: MaxPercentageCpu
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
    startLine: 522
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nOptional. The name of the pair.\r\n"
  example: []
  syntax:
    content: >-
      public double ? MaxPercentageCpu

      {

          get;

          set;

      }
    content.vb: Public Property MaxPercentageCpu As Double?
    parameters: []
    return:
      type: System.Nullable{System.Double}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits
  langs:
  - csharp
  - vb
  name: SiteLimits()
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.SiteLimits.SiteLimits()
  type: Constructor
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
    startLine: 531
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\r\nInitializes a new instance of the SiteLimits class.\r\n"
  example: []
  syntax:
    content: public SiteLimits()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.WebSites.Models
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Nullable{System.Int64}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int64>
  fullName: System.Nullable<System.Int64>
  fullname.vb: System.Nullable(Of System.Int64)
  name.vb: Nullable(Of Int64)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Int64
    name: Int64
    fullName: System.Int64
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Int64
    name: Int64
    fullName: System.Int64
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Nullable{System.Double}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Double>
  fullName: System.Nullable<System.Double>
  fullname.vb: System.Nullable(Of System.Double)
  name.vb: Nullable(Of Double)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Double
    name: Double
    fullName: System.Double
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Double
    name: Double
    fullName: System.Double
    isExternal: true
  - name: )
    fullName: )
