items:
- uid: Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult
  commentId: T:Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult
  id: WebSiteGetConfigurationResult
  parent: Microsoft.Azure.Management.WebSites.Models
  children:
  - Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult.#ctor
  - Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult.Resource
  langs:
  - csharp
  - vb
  name: WebSiteGetConfigurationResult
  fullName: Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult
  type: Class
  source:
    remote:
      path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: WebSiteGetConfigurationResult
    path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResult.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nConfig for the website.\r\n"
  example: []
  syntax:
    content: 'public class WebSiteGetConfigurationResult : AzureOperationResponse'
    content.vb: >-
      Public Class WebSiteGetConfigurationResult

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult.Resource
  commentId: P:Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult.Resource
  id: Resource
  parent: Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult
  langs:
  - csharp
  - vb
  name: Resource
  fullName: Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult.Resource
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Resource
    path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResult.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nOptional. Configuration for a site.\r\n"
  example: []
  syntax:
    content: >-
      public WebSiteConfigurationEnvelope Resource

      {

          get;

          set;

      }
    content.vb: Public Property Resource As WebSiteConfigurationEnvelope
    parameters: []
    return:
      type: Microsoft.Azure.Management.WebSites.Models.WebSiteConfigurationEnvelope
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult.#ctor
  commentId: M:Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult
  langs:
  - csharp
  - vb
  name: WebSiteGetConfigurationResult()
  fullName: Microsoft.Azure.Management.WebSites.Models.WebSiteGetConfigurationResult.WebSiteGetConfigurationResult()
  type: Constructor
  source:
    remote:
      path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteGetConfigurationResult.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nInitializes a new instance of the WebSiteGetConfigurationResult\r\nclass.\r\n"
  example: []
  syntax:
    content: public WebSiteGetConfigurationResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.Azure.Management.WebSites.Models
  fullName: Microsoft.Azure.Management.WebSites.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.WebSites.Models.WebSiteConfigurationEnvelope
  parent: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: WebSiteConfigurationEnvelope
  fullName: Microsoft.Azure.Management.WebSites.Models.WebSiteConfigurationEnvelope
