items:
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  commentId: T:Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  id: ContinuousWebJobSettingsResponse
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models
  children:
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.#ctor
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.IsSingleton
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  langs:
  - csharp
  - vb
  name: ContinuousWebJobSettingsResponse
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  type: Class
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ContinuousWebJobSettingsResponse
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\r\nThe continuous WebJob settings operation response.\r\n"
  example: []
  syntax:
    content: 'public class ContinuousWebJobSettingsResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ContinuousWebJobSettingsResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.IsSingleton
  commentId: P:Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.IsSingleton
  id: IsSingleton
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  langs:
  - csharp
  - vb
  name: IsSingleton
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.IsSingleton
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: IsSingleton
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\r\nOptional. If a continuous job is set as singleton it'll run only on\r\na single instance opposed to running on all instances.\r\n"
  example: []
  syntax:
    content: >-
      public bool ? IsSingleton

      {

          get;

          set;

      }
    content.vb: Public Property IsSingleton As Boolean?
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  commentId: P:Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  id: ShutdownGraceTimeInSeconds
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  langs:
  - csharp
  - vb
  name: ShutdownGraceTimeInSeconds
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ShutdownGraceTimeInSeconds
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
    startLine: 50
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\r\nOptional. Specify the time in seconds to wait for the WebJob to\r\ngracefully shutdown.\r\n"
  example: []
  syntax:
    content: >-
      public int ? ShutdownGraceTimeInSeconds

      {

          get;

          set;

      }
    content.vb: Public Property ShutdownGraceTimeInSeconds As Integer?
    parameters: []
    return:
      type: System.Nullable{System.Int32}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.#ctor
  commentId: M:Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  langs:
  - csharp
  - vb
  name: ContinuousWebJobSettingsResponse()
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.ContinuousWebJobSettingsResponse()
  type: Constructor
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: BradysOpsPlayground/src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
    startLine: 60
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\r\nInitializes a new instance of the ContinuousWebJobSettingsResponse\r\nclass.\r\n"
  example: []
  syntax:
    content: public ContinuousWebJobSettingsResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models
  isExternal: false
  name: Microsoft.WindowsAzure.WebSitesExtensions.Models
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  fullname.vb: System.Nullable(Of System.Boolean)
  name.vb: Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  fullname.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Int32
    name: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    fullName: )
