items:
- uid: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult
  commentId: T:Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult
  id: ApplicationGetResult
  parent: Microsoft.Azure.Graph.RBAC.Models
  children:
  - Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult.#ctor
  - Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult.Application
  langs:
  - csharp
  - vb
  name: ApplicationGetResult
  fullName: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult
  type: Class
  source:
    remote:
      path: BradysOpsPlayground/src/Graph.RBAC/Graph.RBAC/Generated/Models/ApplicationGetResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ApplicationGetResult
    path: BradysOpsPlayground/src/Graph.RBAC/Graph.RBAC/Generated/Models/ApplicationGetResult.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Graph.RBAC
  namespace: Microsoft.Azure.Graph.RBAC.Models
  summary: "\r\nServer response for Get application information API call\r\n"
  example: []
  syntax:
    content: 'public class ApplicationGetResult : AzureOperationResponse'
    content.vb: >-
      Public Class ApplicationGetResult

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult.Application
  commentId: P:Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult.Application
  id: Application
  parent: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult
  langs:
  - csharp
  - vb
  name: Application
  fullName: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult.Application
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/Graph.RBAC/Graph.RBAC/Generated/Models/ApplicationGetResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Application
    path: BradysOpsPlayground/src/Graph.RBAC/Graph.RBAC/Generated/Models/ApplicationGetResult.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Graph.RBAC
  namespace: Microsoft.Azure.Graph.RBAC.Models
  summary: "\r\nOptional. Active Directory application information\r\n"
  example: []
  syntax:
    content: >-
      public Application Application

      {

          get;

          set;

      }
    content.vb: Public Property Application As Application
    parameters: []
    return:
      type: Microsoft.Azure.Graph.RBAC.Models.Application
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult.#ctor
  commentId: M:Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult
  langs:
  - csharp
  - vb
  name: ApplicationGetResult()
  fullName: Microsoft.Azure.Graph.RBAC.Models.ApplicationGetResult.ApplicationGetResult()
  type: Constructor
  source:
    remote:
      path: BradysOpsPlayground/src/Graph.RBAC/Graph.RBAC/Generated/Models/ApplicationGetResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: BradysOpsPlayground/src/Graph.RBAC/Graph.RBAC/Generated/Models/ApplicationGetResult.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Graph.RBAC
  namespace: Microsoft.Azure.Graph.RBAC.Models
  summary: "\r\nInitializes a new instance of the ApplicationGetResult class.\r\n"
  example: []
  syntax:
    content: public ApplicationGetResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Graph.RBAC.Models
  isExternal: false
  name: Microsoft.Azure.Graph.RBAC.Models
  fullName: Microsoft.Azure.Graph.RBAC.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Graph.RBAC.Models.Application
  parent: Microsoft.Azure.Graph.RBAC.Models
  isExternal: false
  name: Application
  fullName: Microsoft.Azure.Graph.RBAC.Models.Application
