items:
- uid: Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult
  commentId: T:Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult
  id: WebSiteAppSettingsResult
  parent: Microsoft.Azure.Management.WebSites.Models
  children:
  - Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult.#ctor
  - Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult.Resource
  langs:
  - csharp
  - vb
  name: WebSiteAppSettingsResult
  fullName: Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult
  type: Class
  source:
    remote:
      path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteAppSettingsResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: WebSiteAppSettingsResult
    path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteAppSettingsResult.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nList of app settings for the website.\r\n"
  example: []
  syntax:
    content: 'public class WebSiteAppSettingsResult : AzureOperationResponse'
    content.vb: >-
      Public Class WebSiteAppSettingsResult

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult.Resource
  commentId: P:Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult.Resource
  id: Resource
  parent: Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult
  langs:
  - csharp
  - vb
  name: Resource
  fullName: Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult.Resource
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteAppSettingsResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Resource
    path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteAppSettingsResult.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nOptional. Application settings configuration for a site.\r\n"
  example: []
  syntax:
    content: >-
      public WebSiteAppSettingsEnvelope Resource

      {

          get;

          set;

      }
    content.vb: Public Property Resource As WebSiteAppSettingsEnvelope
    parameters: []
    return:
      type: Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsEnvelope
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult.#ctor
  commentId: M:Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult
  langs:
  - csharp
  - vb
  name: WebSiteAppSettingsResult()
  fullName: Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsResult.WebSiteAppSettingsResult()
  type: Constructor
  source:
    remote:
      path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteAppSettingsResult.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: BradysOpsPlayground/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteAppSettingsResult.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.WebSites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\r\nInitializes a new instance of the WebSiteAppSettingsResult class.\r\n"
  example: []
  syntax:
    content: public WebSiteAppSettingsResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.Azure.Management.WebSites.Models
  fullName: Microsoft.Azure.Management.WebSites.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsEnvelope
  parent: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: WebSiteAppSettingsEnvelope
  fullName: Microsoft.Azure.Management.WebSites.Models.WebSiteAppSettingsEnvelope
