items:
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings
  id: DebugSettings
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  children:
  - Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.#ctor
  - Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.#ctor(System.Boolean)
  - Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.BootDiagnosticsEnabled
  - Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.ConsoleScreenshotBlobUri
  - Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.SerialOutputBlobUri
  langs:
  - csharp
  - vb
  name: DebugSettings
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings
  type: Class
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: DebugSettings
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
    startLine: 29
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nThe parameters Azure uses to set debug settings for console output.\r\n"
  example: []
  syntax:
    content: public class DebugSettings
    content.vb: Public Class DebugSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.BootDiagnosticsEnabled
  commentId: P:Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.BootDiagnosticsEnabled
  id: BootDiagnosticsEnabled
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings
  langs:
  - csharp
  - vb
  name: BootDiagnosticsEnabled
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.BootDiagnosticsEnabled
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: BootDiagnosticsEnabled
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
    startLine: 36
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nRequired. Enable or disable boot diagnostics.\r\n"
  example: []
  syntax:
    content: >-
      public bool BootDiagnosticsEnabled

      {

          get;

          set;

      }
    content.vb: Public Property BootDiagnosticsEnabled As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.ConsoleScreenshotBlobUri
  commentId: P:Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.ConsoleScreenshotBlobUri
  id: ConsoleScreenshotBlobUri
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings
  langs:
  - csharp
  - vb
  name: ConsoleScreenshotBlobUri
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.ConsoleScreenshotBlobUri
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ConsoleScreenshotBlobUri
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
    startLine: 47
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nOptional. Blob uri for console screen shot.\r\n"
  example: []
  syntax:
    content: >-
      public Uri ConsoleScreenshotBlobUri

      {

          get;

          set;

      }
    content.vb: Public Property ConsoleScreenshotBlobUri As Uri
    parameters: []
    return:
      type: System.Uri
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.SerialOutputBlobUri
  commentId: P:Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.SerialOutputBlobUri
  id: SerialOutputBlobUri
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings
  langs:
  - csharp
  - vb
  name: SerialOutputBlobUri
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.SerialOutputBlobUri
  type: Property
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: SerialOutputBlobUri
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
    startLine: 58
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nOptional. Blob uri for serial output.\r\n"
  example: []
  syntax:
    content: >-
      public Uri SerialOutputBlobUri

      {

          get;

          set;

      }
    content.vb: Public Property SerialOutputBlobUri As Uri
    parameters: []
    return:
      type: System.Uri
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings
  langs:
  - csharp
  - vb
  name: DebugSettings()
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.DebugSettings()
  type: Constructor
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
    startLine: 67
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nInitializes a new instance of the DebugSettings class.\r\n"
  example: []
  syntax:
    content: public DebugSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.#ctor(System.Boolean)
  commentId: M:Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings
  langs:
  - csharp
  - vb
  name: DebugSettings(Boolean)
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DebugSettings.DebugSettings(System.Boolean)
  type: Constructor
  source:
    remote:
      path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: BradysOpsPlayground/src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DebugSettings.cs
    startLine: 75
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\r\nInitializes a new instance of the DebugSettings class with required\r\narguments.\r\n"
  example: []
  syntax:
    content: public DebugSettings(bool bootDiagnosticsEnabled)
    content.vb: Public Sub New(bootDiagnosticsEnabled As Boolean)
    parameters:
    - id: bootDiagnosticsEnabled
      type: System.Boolean
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Compute.Models
  fullName: Microsoft.WindowsAzure.Management.Compute.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  fullName: System.Uri
