items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  id: ServerDisasterRecoveryConfigurationListResponse
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.System#Collections#IEnumerable#GetEnumerator
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationListResponse
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ServerDisasterRecoveryConfigurationListResponse
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
    startLine: 34
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nRepresents the response to a List Azure Sql Server disaster recovery\r\nconfiguration request.\r\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfigurationListResponse : AzureOperationResponse, IEnumerable<ServerDisasterRecoveryConfiguration>, IEnumerable'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfigurationListResponse

          Inherits AzureOperationResponse

          Implements IEnumerable(Of ServerDisasterRecoveryConfiguration), IEnumerable
  inheritance:
  - System.Object
  implements:
  - System.Collections.Generic.IEnumerable{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}
  - System.Collections.IEnumerable
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
  id: ServerDisasterRecoveryConfigurations
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurations
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ServerDisasterRecoveryConfigurations
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
    startLine: 42
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nOptional. Gets or sets the list of Azure Sql Server disaster\r\nrecovery configurations.\r\n"
  example: []
  syntax:
    content: >-
      public IList<ServerDisasterRecoveryConfiguration> ServerDisasterRecoveryConfigurations

      {

          get;

          set;

      }
    content.vb: Public Property ServerDisasterRecoveryConfigurations As IList(Of ServerDisasterRecoveryConfiguration)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationListResponse()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurationListResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nInitializes a new instance of the\r\nServerDisasterRecoveryConfigurationListResponse class.\r\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationListResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator
  id: GetEnumerator
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  langs:
  - csharp
  - vb
  name: GetEnumerator()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator()
  type: Method
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: GetEnumerator
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
    startLine: 60
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nGets the sequence of ServerDisasterRecoveryConfigurations.\r\n"
  example: []
  syntax:
    content: public IEnumerator<ServerDisasterRecoveryConfiguration> GetEnumerator()
    content.vb: Public Function GetEnumerator As IEnumerator(Of ServerDisasterRecoveryConfiguration)
    return:
      type: System.Collections.Generic.IEnumerator{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.System#Collections#IEnumerable#GetEnumerator
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.System#Collections#IEnumerable#GetEnumerator
  id: System#Collections#IEnumerable#GetEnumerator
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  langs:
  - csharp
  - vb
  name: IEnumerable.GetEnumerator()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.System.Collections.IEnumerable.GetEnumerator()
  type: Method
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: System.Collections.IEnumerable.GetEnumerator
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
    startLine: 68
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nGets the sequence of ServerDisasterRecoveryConfigurations.\r\n"
  example: []
  syntax:
    content: IEnumerator IEnumerable.GetEnumerator()
    content.vb: Function System.Collections.IEnumerable.GetEnumerator As IEnumerator Implements IEnumerable.GetEnumerator
    return:
      type: System.Collections.IEnumerator
  name.vb: System.Collections.IEnumerable.GetEnumerator()
references:
- uid: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Collections.Generic.IEnumerable{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<ServerDisasterRecoveryConfiguration>
  fullName: System.Collections.Generic.IEnumerable<Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration>
  fullname.vb: System.Collections.Generic.IEnumerable(Of Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration)
  name.vb: IEnumerable(Of ServerDisasterRecoveryConfiguration)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
    name: ServerDisasterRecoveryConfiguration
    fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
    name: ServerDisasterRecoveryConfiguration
    fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  - name: )
    fullName: )
- uid: System.Collections.IEnumerable
  parent: System.Collections
  isExternal: true
  name: IEnumerable
  fullName: System.Collections.IEnumerable
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.IEnumerable`1
  parent: System.Collections.Generic
  isExternal: true
  name: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  fullname.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Collections
  isExternal: false
  name: System.Collections
  fullName: System.Collections
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<ServerDisasterRecoveryConfiguration>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration)
  name.vb: IList(Of ServerDisasterRecoveryConfiguration)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
    name: ServerDisasterRecoveryConfiguration
    fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
    name: ServerDisasterRecoveryConfiguration
    fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic.IEnumerator{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerator`1
  name: IEnumerator<ServerDisasterRecoveryConfiguration>
  fullName: System.Collections.Generic.IEnumerator<Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration>
  fullname.vb: System.Collections.Generic.IEnumerator(Of Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration)
  name.vb: IEnumerator(Of ServerDisasterRecoveryConfiguration)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerator`1
    name: IEnumerator
    fullName: System.Collections.Generic.IEnumerator
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
    name: ServerDisasterRecoveryConfiguration
    fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerator`1
    name: IEnumerator
    fullName: System.Collections.Generic.IEnumerator
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
    name: ServerDisasterRecoveryConfiguration
    fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  - name: )
    fullName: )
- uid: System.Collections.Generic.IEnumerator`1
  parent: System.Collections.Generic
  isExternal: true
  name: IEnumerator<T>
  fullName: System.Collections.Generic.IEnumerator<T>
  fullname.vb: System.Collections.Generic.IEnumerator(Of T)
  name.vb: IEnumerator(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerator`1
    name: IEnumerator
    fullName: System.Collections.Generic.IEnumerator
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerator`1
    name: IEnumerator
    fullName: System.Collections.Generic.IEnumerator
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: true
  name: IEnumerator
  fullName: System.Collections.IEnumerator
