items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  id: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nResponse for long running Azure Sql server disaster recovery\r\nconfiguration operation.\r\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfigurationCreateOrUpdateResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfigurationCreateOrUpdateResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
  id: Error
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: Error
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Error
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nOptional.\r\n"
  example: []
  syntax:
    content: >-
      public ErrorResponse Error

      {

          get;

          set;

      }
    content.vb: Public Property Error As ErrorResponse
    parameters: []
    return:
      type: Microsoft.Azure.Management.Sql.Models.ErrorResponse
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
  id: OperationStatusLink
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: OperationStatusLink
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: OperationStatusLink
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nOptional.\r\n"
  example: []
  syntax:
    content: >-
      public string OperationStatusLink

      {

          get;

          set;

      }
    content.vb: Public Property OperationStatusLink As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
  id: RetryAfter
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: RetryAfter
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: RetryAfter
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 61
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nOptional.\r\n"
  example: []
  syntax:
    content: >-
      public int RetryAfter

      {

          get;

          set;

      }
    content.vb: Public Property RetryAfter As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
  id: ServerDisasterRecoveryConfiguration
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ServerDisasterRecoveryConfiguration
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 73
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nOptional. Gets or sets the object that represents the Azure Sql\r\nServer disaster recovery configuration.\r\n"
  example: []
  syntax:
    content: >-
      public ServerDisasterRecoveryConfiguration ServerDisasterRecoveryConfiguration

      {

          get;

          set;

      }
    content.vb: Public Property ServerDisasterRecoveryConfiguration As ServerDisasterRecoveryConfiguration
    parameters: []
    return:
      type: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
  id: Status
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: Status
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Status
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 84
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nOptional.\r\n"
  example: []
  syntax:
    content: >-
      public OperationStatus Status

      {

          get;

          set;

      }
    content.vb: Public Property Status As OperationStatus
    parameters: []
    return:
      type: OperationStatus
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 94
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nInitializes a new instance of the\r\nServerDisasterRecoveryConfigurationCreateOrUpdateResponse class.\r\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationCreateOrUpdateResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Sql.Models.ErrorResponse
  parent: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: ErrorResponse
  fullName: Microsoft.Azure.Management.Sql.Models.ErrorResponse
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  fullName: System.Int32
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  parent: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
- uid: OperationStatus
  isExternal: true
  name: OperationStatus
  fullName: OperationStatus
