items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  id: ServerDisasterRecoveryConfiguration
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor(System.String)
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ServerDisasterRecoveryConfiguration
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nRepresents an Azure SQL Server disaster recovery configuration.\r\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfiguration : ResourceBaseExtended'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfiguration

          Inherits ResourceBaseExtended
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties
  id: Properties
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  langs:
  - csharp
  - vb
  name: Properties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Properties
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nOptional. Gets or sets the properties representing the resource.\r\n"
  example: []
  syntax:
    content: >-
      public ServerDisasterRecoveryConfigurationProperties Properties

      {

          get;

          set;

      }
    content.vb: Public Property Properties As ServerDisasterRecoveryConfigurationProperties
    parameters: []
    return:
      type: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfiguration()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.ServerDisasterRecoveryConfiguration()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nInitializes a new instance of the\r\nServerDisasterRecoveryConfiguration class.\r\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor(System.String)
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfiguration(String)
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.ServerDisasterRecoveryConfiguration(System.String)
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nInitializes a new instance of the\r\nServerDisasterRecoveryConfiguration class with required arguments.\r\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfiguration(string location)
    content.vb: Public Sub New(location As String)
    parameters:
    - id: location
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  parent: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: ServerDisasterRecoveryConfigurationProperties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
