items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse
  id: ServerDisasterRecoveryConfigurationGetResponse
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationGetResponse
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ServerDisasterRecoveryConfigurationGetResponse
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nRepresents the response to a get server disaster recovery configuration\r\nrequest.\r\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfigurationGetResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfigurationGetResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
  id: ServerDisasterRecoveryConfiguration
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ServerDisasterRecoveryConfiguration
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
    startLine: 40
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nOptional. Gets or sets the Azure Sql Server disaster recovery\r\nconfiguration.\r\n"
  example: []
  syntax:
    content: >-
      public ServerDisasterRecoveryConfiguration ServerDisasterRecoveryConfiguration

      {

          get;

          set;

      }
    content.vb: Public Property ServerDisasterRecoveryConfiguration As ServerDisasterRecoveryConfiguration
    parameters: []
    return:
      type: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationGetResponse()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfigurationGetResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nInitializes a new instance of the\r\nServerDisasterRecoveryConfigurationGetResponse class.\r\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationGetResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  parent: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
