items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  id: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties,System.String)
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nCreate or update Azure SQL Server disaster recovery configuration\r\nparameters.\r\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfigurationCreateOrUpdateParameters : ResourceBase'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfigurationCreateOrUpdateParameters

          Inherits ResourceBase
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
  id: Properties
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: Properties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Properties
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nRequired. Gets or sets the properties of the request.\r\n"
  example: []
  syntax:
    content: >-
      public ServerDisasterRecoveryConfigurationCreateOrUpdateProperties Properties

      {

          get;

          set;

      }
    content.vb: Public Property Properties As ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
    parameters: []
    return:
      type: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nInitializes a new instance of the\r\nServerDisasterRecoveryConfigurationCreateOrUpdateParameters class.\r\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationCreateOrUpdateParameters()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties,System.String)
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties,System.String)
  id: '#ctor(Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties,System.String)'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters(ServerDisasterRecoveryConfigurationCreateOrUpdateProperties, String)
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters(Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties, System.String)
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
    startLine: 58
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\r\nInitializes a new instance of the\r\nServerDisasterRecoveryConfigurationCreateOrUpdateParameters class\r\nwith required arguments.\r\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationCreateOrUpdateParameters(ServerDisasterRecoveryConfigurationCreateOrUpdateProperties properties, string location)
    content.vb: Public Sub New(properties As ServerDisasterRecoveryConfigurationCreateOrUpdateProperties, location As String)
    parameters:
    - id: properties
      type: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
    - id: location
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  parent: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
