items:
- uid: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings
  commentId: T:Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings
  id: HttpConnectivitySettings
  parent: Microsoft.Azure.Management.HDInsight.Models
  children:
  - Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.#ctor
  - Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpPassword
  - Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpUserEnabled
  - Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpUsername
  langs:
  - csharp
  - vb
  name: HttpConnectivitySettings
  fullName: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/HttpConnectivitySettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: HttpConnectivitySettings
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/HttpConnectivitySettings.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nThe payload for a Configure HTTP settings request.\r\n"
  example: []
  syntax:
    content: 'public class HttpConnectivitySettings : AzureOperationResponse'
    content.vb: >-
      Public Class HttpConnectivitySettings

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpPassword
  commentId: P:Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpPassword
  id: HttpPassword
  parent: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings
  langs:
  - csharp
  - vb
  name: HttpPassword
  fullName: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpPassword
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/HttpConnectivitySettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: HttpPassword
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/HttpConnectivitySettings.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nOptional. Gets or sets the http user password.\r\n"
  example: []
  syntax:
    content: >-
      public string HttpPassword

      {

          get;

          set;

      }
    content.vb: Public Property HttpPassword As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpUserEnabled
  commentId: P:Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpUserEnabled
  id: HttpUserEnabled
  parent: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings
  langs:
  - csharp
  - vb
  name: HttpUserEnabled
  fullName: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpUserEnabled
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/HttpConnectivitySettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: HttpUserEnabled
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/HttpConnectivitySettings.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nOptional. Gets or sets the whether or not HTTP is enabled.\r\n"
  example: []
  syntax:
    content: >-
      public bool HttpUserEnabled

      {

          get;

          set;

      }
    content.vb: Public Property HttpUserEnabled As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpUsername
  commentId: P:Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpUsername
  id: HttpUsername
  parent: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings
  langs:
  - csharp
  - vb
  name: HttpUsername
  fullName: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpUsername
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/HttpConnectivitySettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: HttpUsername
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/HttpConnectivitySettings.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nOptional. Gets or sets the http username.\r\n"
  example: []
  syntax:
    content: >-
      public string HttpUsername

      {

          get;

          set;

      }
    content.vb: Public Property HttpUsername As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.#ctor
  commentId: M:Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings
  langs:
  - csharp
  - vb
  name: HttpConnectivitySettings()
  fullName: Microsoft.Azure.Management.HDInsight.Models.HttpConnectivitySettings.HttpConnectivitySettings()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/HttpConnectivitySettings.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/HttpConnectivitySettings.cs
    startLine: 68
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nInitializes a new instance of the HttpConnectivitySettings class.\r\n"
  example: []
  syntax:
    content: public HttpConnectivitySettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.HDInsight.Models
  isExternal: false
  name: Microsoft.Azure.Management.HDInsight.Models
  fullName: Microsoft.Azure.Management.HDInsight.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  fullName: System.Boolean
