items:
- uid: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse
  commentId: T:Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse
  id: ClusterConfigurationsResponse
  parent: Microsoft.Azure.Management.HDInsight.Models
  children:
  - Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.#ctor
  - Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration
  langs:
  - csharp
  - vb
  name: ClusterConfigurationsResponse
  fullName: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: ClusterConfigurationsResponse
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nThe Cluster Configurations operation response.\r\n"
  example: []
  syntax:
    content: 'public class ClusterConfigurationsResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ClusterConfigurationsResponse

          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration
  commentId: P:Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration
  id: Configuration
  parent: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse
  langs:
  - csharp
  - vb
  name: Configuration
  fullName: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: Configuration
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nOptional.\r\n"
  example: []
  syntax:
    content: >-
      public IDictionary<string, string> Configuration

      {

          get;

          set;

      }
    content.vb: Public Property Configuration As IDictionary(Of String, String)
    parameters: []
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.String}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.#ctor
  commentId: M:Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse
  langs:
  - csharp
  - vb
  name: ClusterConfigurationsResponse()
  fullName: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.ClusterConfigurationsResponse()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nInitializes a new instance of the ClusterConfigurationsResponse\r\nclass.\r\n"
  example: []
  syntax:
    content: public ClusterConfigurationsResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.HDInsight.Models
  isExternal: false
  name: Microsoft.Azure.Management.HDInsight.Models
  fullName: Microsoft.Azure.Management.HDInsight.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.IDictionary{System.String,System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IDictionary`2
  name: IDictionary<String, String>
  fullName: System.Collections.Generic.IDictionary<System.String, System.String>
  fullname.vb: System.Collections.Generic.IDictionary(Of System.String, System.String)
  name.vb: IDictionary(Of String, String)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: System.Collections.Generic.IDictionary`2
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<TKey, TValue>
  fullName: System.Collections.Generic.IDictionary<TKey, TValue>
  fullname.vb: System.Collections.Generic.IDictionary(Of TKey, TValue)
  name.vb: IDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    fullName: <
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
