items:
- uid: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  commentId: T:Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  id: RDPSettingsParameters
  parent: Microsoft.Azure.Management.HDInsight.Models
  children:
  - Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor
  - Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor(Microsoft.Azure.Management.HDInsight.Models.OsProfile)
  - Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile
  langs:
  - csharp
  - vb
  name: RDPSettingsParameters
  fullName: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  type: Class
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: RDPSettingsParameters
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nParameters specifying the data factory gateway definition for a create\r\nor update operation.\r\n"
  example: []
  syntax:
    content: public class RDPSettingsParameters
    content.vb: Public Class RDPSettingsParameters
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile
  commentId: P:Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile
  id: OsProfile
  parent: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  langs:
  - csharp
  - vb
  name: OsProfile
  fullName: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile
  type: Property
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: OsProfile
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nRequired. Gets or sets the definition of a data factory gateway to\r\nbe created or updated.\r\n"
  example: []
  syntax:
    content: >-
      public OsProfile OsProfile

      {

          get;

          set;

      }
    content.vb: Public Property OsProfile As OsProfile
    parameters: []
    return:
      type: Microsoft.Azure.Management.HDInsight.Models.OsProfile
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor
  commentId: M:Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  langs:
  - csharp
  - vb
  name: RDPSettingsParameters()
  fullName: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.RDPSettingsParameters()
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nInitializes a new instance of the RDPSettingsParameters class.\r\n"
  example: []
  syntax:
    content: public RDPSettingsParameters()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor(Microsoft.Azure.Management.HDInsight.Models.OsProfile)
  commentId: M:Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor(Microsoft.Azure.Management.HDInsight.Models.OsProfile)
  id: '#ctor(Microsoft.Azure.Management.HDInsight.Models.OsProfile)'
  parent: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  langs:
  - csharp
  - vb
  name: RDPSettingsParameters(OsProfile)
  fullName: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.RDPSettingsParameters(Microsoft.Azure.Management.HDInsight.Models.OsProfile)
  type: Constructor
  source:
    remote:
      path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
      branch: master
      repo: https://github.com/bradygaster/BradysOpsPlayground.git
    id: .ctor
    path: src/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\r\nInitializes a new instance of the RDPSettingsParameters class with\r\nrequired arguments.\r\n"
  example: []
  syntax:
    content: public RDPSettingsParameters(OsProfile osProfile)
    content.vb: Public Sub New(osProfile As OsProfile)
    parameters:
    - id: osProfile
      type: Microsoft.Azure.Management.HDInsight.Models.OsProfile
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.HDInsight.Models
  isExternal: false
  name: Microsoft.Azure.Management.HDInsight.Models
  fullName: Microsoft.Azure.Management.HDInsight.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.HDInsight.Models.OsProfile
  parent: Microsoft.Azure.Management.HDInsight.Models
  isExternal: false
  name: OsProfile
  fullName: Microsoft.Azure.Management.HDInsight.Models.OsProfile
